@ This is the source code for a piece called Whisper Song in 53 EDO for Bass Flute, Finger Piano, cello, percussion, and winds. I wrote it in 2007.
@ The code uses a text based front end to csound to load sample files and translate words into sound.
@ The purpose here is to show how I made it possible to create trills bewteen just intonation chords with variable sized intervals.
l; Name: sing53   05/23/07 10:00pm
l; Name: sing53   05/21/07  8:28pm
l; Name: sing53   05/21/07  2:43pm l; Name: sing53   05/20/07  5:25pm l; Name: sing53   05/15/07  7:24am
l; Name: sing53   05/13/07  2:33pm l; Name: sing53   05/10/07  5:20am l; Name: sing53   05/08/07 10:39am
l; Name: sing53   05/08/07  4:05pm l; Name: sing53   05/07/07  8:36pm l; Name: sing53   05/07/07 12:59pm
l; Name: sing53   04/30/07  9:48pm l; Name: sing53   04/30/07  1:40pm l; Name: sing53   04/27/07 12:42pm
l; Name: sing53   04/26/07  4:25pm l; Name: sing53   04/24/07  5:26pm l; Name: sing53   04/23/07  2:33pm
l; Name: sing53   04/21/07  2:33pm l; Name: sing53   04/19/07 12:37pm l; Name: sing53   04/18/07 12:42pm
l; Name: sing53   04/17/07  3:37pm l; Name: sing53   04/14/07  9:20am l; Name: sing53   04/07/07  2:10pm
l; Name: sing53   04/05/07  3:12pm l; Name: sing53   04/04/07  7:48pm l; Name: sing53   04/03/07  4:05pm
l; Name: sing53   04/02/07 10:41am l; Name: sing53   04/01/07  1:48pm l; Name: sing53   03/30/07  9:58am
l; Name: sing53   03/29/07  1:14pm l; Name: sing53   03/28/07 11:05am l; Name: sing53   03/27/07  1:53pm
l; Name: sing53   03/23/07  3:32pm l; Name: sing53   03/22/07  6:18pm l; Name: sing53   03/22/07 11:47am
l; Name: sing53   03/18/07  1:23pm l; Name: sing53   03/17/07  9:34am l; Name: sing53   03/14/07  2:09pm
l; Name: sing53   03/12/07  1:51pm l; Name: sing53   03/11/07 10:29am l; Name: sing53   03/10/07  9:49am
l; Name: sing53   03/08/07  2:44pm l; Name: sing53   03/08/07  8:56am l; Name: sing53   03/04/07  9:13am
l; Name: sing53   03/03/07  2:47pm l; Name: sing53   02/27/07  9:15am l; Name: sing53   02/26/07  1:37pm
l; Name: sing53   02/24/07  9:59am l; Name: sing53   02/22/07  4:41pm l; Name: sing53   02/21/07  7:46pm
l; Name: sing53   02/21/07  8:13am l; Name: sing53   02/20/07  1:35pm l; Name: sing53   02/19/07  9:45pm
l; Name: sing53   02/16/07  3:26pm l; Name: sing53   02/14/07  4:18pm l; Name: sing53   02/13/07 10:46am
l; Name: sing53   02/12/07  4:30pm l; Name: sing53   02/10/07  7:08am l; Name: sing53   02/03/07  1:06pm
l;
l; Title:        Sing in 53
l; Some ideas
l;    - Some of the changes are way too abrupt.
l;    - Need a way to control the overall velocity like you can the speed.
l;    - Cello? Sure, but less dense. Use some chords.
l;    - turn up the arpeggio some more, turn down some of the percussion, perhaps a different volume level for each sound
l;    - Alto flute a sixth above in harmony?
l;    - Another idea: What about a minor in the otonality? 10:12:15 E5/4 G3/2 B15/8
l;                    Or a major in the utonality? 1/(15/12/10) D16/15 F4/3 A8/5
l;    - M. Keiser on Glass -  Chord progression see
l;               http://suburbanscene.blogspot.com/2006/01/philip-glass-wise-remark.html
l;               Ironically, Glass' music is often criticize for its terrible sameness- "it all
l;               sounds the same" kind of thing, and in the last 30 years how far has he deviated
l;               from his origins? not very far at all. His chord progressions can be
l;               horrifyingly hackneyed. "its the philip glass chord progression!" you might say
l;               to yourself when listening to anything he's written in the last 20 years. He
l;               seems to use it in all music after the mid 80s.... major on the tonic, chromatic
l;               shift down to minor, back to an inversion of the major chord, then to the...what
l;               do you call it... arg, theory terminology slipping away from me, the "dominant"
l;               for the minor (i like to think of it as this, hopefully you know what the hell
l;               im talking about) and then back to the relative minor, and then back to the
l;               major on the tonic, and again and again and again. In only slight variations
l;               this appears in dozens of pieces and operas and on and on and on. Minimalism
l;               still exists- not in his music, but in his musical output as-a-whole.
l;    - Kyle Gann said
l;               What's less often acknowledged is that, amid all the reams of
l;               three-against-two and G minor-F-E-flat-D chord progressions, cliches rendered
l;               painful by lifelong repetition, he continues to occasionally turn out amazing,
l;               advanced, original pieces of music.
l;           F major
l;           E minor
l;           F major inversion
l;           B minor
l;           D minor
l;           F major
l;    - Partch - Composers can think only in equal temperment,
l;               because it is all they have got to think in.
l;               Music systems are made valid and workable by significant music.
l;               Music systems that are not made valid by significant music,
l;               are so many scraps of paper in a whirlwind.
l;    - Voice of the president
l;    - Kitchen sink singing...
l; Current activities
l;   - There is a bug in that it won't properly set the base note for samples higher than 30 per instrument.
l; done
l<CsoundSynthesizer>
l
l<CsOptions>
@ use the following for writing to a file -G is to create a postscript eps output file of function tables
@-G
l-W -G -m2 -+y -o sflib\sing53.wav
@ use the following for live play
@l-+X1 -b900 -d -m0 -+y
l</CsOptions>
l
l<CsInstruments>
l      sr     = 44100
l      ksmps  =    2 ; any higher than 10 and I hear clicks - use 1 for final take
l;                         typically save 5x processing time by increasing ksmps by 10x
l      nchnls =     2
l      instr   1
l
l; p1 is always 1
l; p2 start time
l; p3 duration
l; p4 velocity, 60-80 works best
l; p5 tone - which tone is this note - 1-100 for Partch scale - maxequal in samples.pas 6/15/06
l; p6 Octave
l; p7 voice
l; p8 stereo - pan from left = 0 to right = 16
l; p9 envelope - one of several function tables for envelopes 1 - 16
l; p10 glissando - one of several function tables to modify pitch
l; p11 upsample - use a sample higher (>0) or lower (<256) than normal
l; p12 envelope for right channel - if blank, use the left channel envelope for both channels
l;
l     ifunc    table   p7,1             ; find the location of the sample wave tables
l     iwavchan table   p7,2             ; is it mono (iwavchan = 1) or stereo sample file (iwavchan = 2)
l                                       ; or are sustain points in separate table iwavchan=3
l     ioct     =       p6+3             ; I am used to Middle C = 6
l     inum     =       p6*12 + int(p5/53*12) ; convert to MIDI note number to pick ftable - why 100, used to be 57
l     ifno2    table   inum, ifunc      ; map midi note number to ftables
l     ifno     =       ifno2 + (p11 < 128 ? p11 : p11-256) ; offset the chosen ftable by parameter 11 - upsample
l     iamp     =       ampdb(p4)                ; velocity input is 60-80 - convert to amplitude
l     i9       =       298-p9                   ; valid envelope table number are 298, 297, 296, 295 etc. - left channel
l     i12      =       298-p12                  ; valid envelope table number are 298, 297, 296, 295 etc. - right channel
l     i10      =       301+p10                  ; valid glissando table number are  301, 302, etc
l;         kamp_l   poscil  iamp, 1/p3, i9           ; create a precise long envelope from a function table for left channel
l;         kamp_r   poscil  iamp, 1/p3, i12          ; create a precise long envelope from a function table for right channel
l     kamp_l   oscil  iamp, 1/p3, i9           ; create an envelope from a function table for left channel
l     kamp_r   oscil  iamp, 1/p3, i12          ; create an envelope from a function table for right channel
l     kpan_l   tablei  p8/16, 4, 1              ; pan with a sine wave using f table #4 - 2st value is reduced to max 1, normalized
l     kpan_r   tablei  1.0 - p8/16, 4, 1        ; inverse of kpan_l
l     ibasno   table   ifno-(3+ifunc), 1  + ifunc     ; get basnot for each ftable
l     icent    table   ifno-(3+ifunc), 2  + ifunc     ; get cents to flatten each note
l     iloop    table   ifno-(3+ifunc), 3  + ifunc     ; get loop or not
l     ibasoct  =       ibasno/12 + 3    ; find the base octave
l     ibascps  =       cpsoct(ibasoct+(icent/1200))
l     ipitch   table   p5, 3  ; convert note number 1-57 to oct.fract format - hand made table 3 of fractions
l     kcps     =       cpspch(ioct+ipitch)  ; convert oct.fract to Hz
l     kcpsm    oscili  1, 1/p3, i10 ; create an set of shift multiplicands from table - glissandi
l     kcps2    =       kcps * kcpsm     ; shift the frequency by values in glissando table
l ;  Four choices: Mono looping, stereo looping, mono no-loop, stereo no-loop
l             if iwavchan = 4 goto akaimono
l             if iloop = 0 goto noloops
l ;  Stereo with loop
l             a3,a4   loscil  1, kcps2, ifno, ibascps; stereo sample with looping
l             goto skipstereo
l         noloops:
l ;  Stereo without looping
l             a3,a4   loscil  1, kcps2, ifno, ibascps,0,1,2 ; stereo sample without looping - note that 1,2 is bogus workaround
l             goto skipstereo
l         akaimono:
l             if iloop = 0 goto noloopm
l ;  Mono with looping
l             a3      loscil  1, kcps2, ifno, ibascps ; mono sampling with loop
l ;            print ifno,ibascps
l             a4 = a3
l             goto skipstereo
l         noloopm:
l ;  Mono without looping
l             a3      loscil  1, kcps2, ifno, ibascps,0,1,2 ; mono AIFF sample without loop
l              ; print p5,p6,ifno ,ibascps,ioct,inum,ifno2,ibasno,icent,ibasoct,ipitch
l              print p5,p6,ifno,p7
l             a4 = a3
l
l         skipstereo:
l ; start comparison sine wave oscillator for fine tuning adjustment testing
l   ;              ihertz = cpspch(ioct+ipitch) ; what frequency are you trying to make
l   ;              print p5, p6, inum, ibasno, icent, ibascps
l   ;              print ipitch, ihertz, ifno  ; show me the tone, octave, frequency, and function table containing the sample
l   ;             a1  oscili 1, .5*kcps, 4   ; 1/4 of a sine wave to compare the sample frequency to
l   ;             a5 = a1 + a3                ; add the sample to the square wave right
l   ;             a6 = a4 + a1                ; and left
l   ;             a3 = a5
l   ;             a4 = a6
l ; end comparison sine wave oscilator
l             a1 = a3 * kamp_l
l             a2 = a4 * kamp_r
l            outs     a1 * kpan_l ,a2 * kpan_r


l ; end comparison sine wave oscilator
l             a1 = a3 * kamp_l
l             a2 = a4 * kamp_r
l             outs     a1 * kpan_l ,a2 * kpan_r
l     endin
l
l;     instr 99
l;       kamp   poscil  1, 1/p3, 1           ; create an envelope from a function table
l;       a6, a7 soundin "sflib/sing53.wav"
l;       outs a6 * kamp, a7 * kamp
l;     endin
l</CsInstruments>
l
l<CsScore>
lf3 0 128 -2
l 0 0.0022642 0.0045283 0.0067925 0.0090566 0.0113208 0.0135849 0.0158491 0.0181132 0.0203774
l 0.0226415 0.0249057 0.0271698 0.0294340 0.0316981 0.0339623 0.0362264 0.0384906 0.0407547 0.0430189
l 0.0452830 0.0475472 0.0498113 0.0520755 0.0543396 0.0566038 0.0588679 0.0611321 0.0633962 0.0656604
l 0.0679245 0.0701887 0.0724528 0.0747170 0.0769811 0.0792453 0.0815094 0.0837736 0.0860377 0.0883019
l 0.0905660 0.0928302 0.0950943 0.0973585 0.0996226 0.1018868 0.1041509 0.1064151 0.1086792 0.1109434
l 0.1132075 0.1154717 0.1177358 0.1200000
@ lf3 0 128 -2 0.0 0.0070672 0.0084467 0.0111731 0.0119443 0.0128298 0.0138573 0.0150637 0.0155140 0.0165004
@ l 0.0182404 0.0203910 0.0231174 0.0247741 0.0266871 0.0289210 0.0315641 0.0347408 0.0359472 0.0378602
@ l 0.0386314 0.0417508 0.0427373 0.0435084 0.0454214 0.0470781 0.0498045 0.0536951 0.0551318 0.0563382
@ l 0.0582512 0.0609776 0.0617488 0.0636618 0.0648682 0.0653185 0.0663049 0.0694243 0.0701955 0.0737652
@ l 0.0745786 0.0764916 0.0772627 0.0782492 0.0813686 0.0840528 0.0849383 0.0852592 0.0857095 0.0884359
@ l 0.0910790 0.0925418 0.0933129 0.0952259 0.0968826 0.0996090 0.1017596 0.1034996 0.1049363 0.1061427
@ l 0.1071702 0.1080557 0.1088269 0.1172736 0.1200000
@ old limited diamond - only notes that are in the diamond
@ lf3 0 128 -2 0.0 0.0111731 0.0119443 0.0128298 0.0138573 0.0150637 0.0165004
@ l0.0182404 0.0203910 0.0231174 0.0247741 0.0266871 0.0289210 0.0315641 0.0315641
@ l0.0347408 0.0359472 0.0386314 0.0386314 0.0417508 0.0435084 0.0454214 0.0498045
@ l0.0498045 0.0498045 0.0536951 0.0551318 0.0563382 0.0582512 0.0617488 0.0636618
@ l0.0648682 0.0663049 0.0701955 0.0701955 0.0701955 0.0745786 0.0764916 0.0782492
@ l0.0813686 0.0813686 0.0840528 0.0852592 0.0884359 0.0884359 0.0910790 0.0933129
@ l0.0952259 0.0968826 0.0996090 0.1017596 0.1034996 0.1049363 0.1061427 0.1071702
@ l0.1080557 0.1088269 0.1200000
lf4 0 1025 9 .25 1 0 ;The first quadrant of a sine for panning
@lf9 0 1025 9 1 .5 2 .25 3 .125 4 .125 0 ; a sort of sawtooth sine wave
;lf9 0 256 10 1 ; sine wave
@lf2 0 256 10 1
; c4 = 72 = middle C = 60 is MIDI standard number
; g3 = 67
; something is wrong with function table 300
;               1st take 2nd take 3rd take 4th take 5th take 6th take sum of takes = size of table
; these are useful for taking a note up or down an octave without moving the sample up or down - built in munchkinization
lf301 0 256 -7   1   256   1                                   ; g0 = no change;
lf302 0 256 -7   1.125 256 1.125                               ; g1 up 9/8
lf303 0 256 -7   1.25  256 1.25                                ; g2 up 5/4
lf304 0 256 -7   1.3333 256 1.3333                             ; g3 up 4/3
lf305 0 256 -7   1.5    256 1.5                                ; g4 up 3/2
lf306 0 256 -7  .875    256 .875                               ; g5 down 7/8
@  minor up and down and back (for example, F G-- D++)
@ f#  t size ty s for e t up a ratio for stay there   down to  stay there   end
lf307 0 1024 -7 1 512 1 0 1.09090909 256 1.09090909 0 .8571429 256 .8571429 0 ; g6  1 2 6 = 11:6 -> 1:1 -> 11/7
lf308 0 1024 -7 1 512 1 0 1.1        256 1.1        0 .9166667 256 .9166667 0 ; g7  2 3 1 = G-- Ab  F
lf309 0 1024 -7 1 512 1 0 1.111111   256 1.111111   0 .9090909 256 .9090909 0 ; g8  3 4 2 = 11:10 -> 11:9 -> 1:1
lf310 0 1024 -7 1 512 1 0 1.125      256 1.125      0 .9000000 256 .9000000 0 ; g9  4 5 3 = A#  C   Ab
lf311 0 1024 -7 1 512 1 0 1.14285714 256 1.14285714 0 .8888889 256 .8888888 0 ; g10 5 6 4 = 11:8 -> 11:7 -> 11:9
@ slide down for gong
lf312 0 256 -7 1 256 1.3; g11
lf313 0 256 -7 1 256 .80; g12
; Glissando up tables min points mid pts max pts mid pts max pts mid pts min mid max mid min mid max ; glide number Ratio
; Glides optimized for 53 tone stepsize:    1.0131641 0.9870069
lf 315 0 256 -7 1 64 1 128 1.0131641 64 1.0131641 ; 77 : 76 _g 14 up 1
lf 316 0 256 -7 1 64 1 128 1.0265016 64 1.0265016 ; 39 : 38 _g 15 up 2
lf 317 0 256 -7 1 64 1 128 1.0400146 64 1.0400146 ; 26 : 25 _g 16 up 3
lf 318 0 256 -7 1 64 1 128 1.0537055 64 1.0537055 ; 20 : 19 _g 17 up 4
lf 319 0 256 -7 1 64 1 128 1.0675766 64 1.0675766 ; 16 : 15 _g 18 up 5
lf 320 0 256 -7 1 64 1 128 1.0816304 64 1.0816304 ; 13 : 12 _g 19 up 6
lf 321 0 256 -7 1 64 1 128 1.0958691 64 1.0958691 ; 11 : 10 _g 20 up 7
lf 322 0 256 -7 1 64 1 128 1.1102953 64 1.1102953 ; 10 : 9 _g 21 up 8
lf 323 0 256 -7 1 64 1 128 1.1249114 64 1.1249114 ; 9 : 8 _g 22 up 9
lf 324 0 256 -7 1 64 1 128 1.1397199 64 1.1397199 ; 8 : 7 _g 23 up 10
lf 325 0 256 -7 1 64 1 128 1.1547233 64 1.1547233 ; 15 : 13 _g 24 up 11
lf 326 0 256 -7 1 64 1 128 1.1699242 64 1.1699242 ; 7 : 6 _g 25 up 12
lf 327 0 256 -7 1 64 1 128 1.1853253 64 1.1853253 ; 19 : 16 _g 26 up 13
lf 328 0 256 -7 1 64 1 128 1.2009291 64 1.2009291 ; 6 : 5 _g 27 up 14
lf 329 0 256 -7 1 64 1 128 1.2167383 64 1.2167383 ; 28 : 23 _g 28 up 15
lf 330 0 256 -7 1 64 1 128 1.2327556 64 1.2327556 ; 16 : 13 _g 29 up 16
lf 331 0 256 -7 1 64 1 128 1.2489838 64 1.2489838 ; 5 : 4 _g 30 up 17
lf 332 0 256 -7 1 64 1 128 1.2654256 64 1.2654256 ; 19 : 15 _g 31 up 18
lf 333 0 256 -7 1 64 1 128 1.2820838 64 1.2820838 ; 9 : 7 _g 32 up 19
lf 334 0 256 -7 1 64 1 128 1.2989613 64 1.2989613 ; 13 : 10 _g 33 up 20
lf 335 0 256 -7 1 64 1 128 1.3160611 64 1.3160611 ; 25 : 19 _g 34 up 21
lf 336 0 256 -7 1 64 1 128 1.3333859 64 1.3333859 ; 4 : 3 _g 35 up 22
lf 337 0 256 -7 1 64 1 128 1.3509387 64 1.3509387 ; 27 : 20 _g 36 up 23
lf 338 0 256 -7 1 64 1 128 1.3687227 64 1.3687227 ; 26 : 19 _g 37 up 24
lf 339 0 256 -7 1 64 1 128 1.3867408 64 1.3867408 ; 11 : 8 _g 38 up 25
lf 340 0 256 -7 1 64 1 128 1.4049960 64 1.4049960 ; 59 : 42 _g 39 up 26
lf 341 0 256 -7 1 64 1 128 1.4234916 64 1.4234916 ; 10 : 7 _g 40 up 27
lf 342 0 256 -7 1 64 1 128 1.4422306 64 1.4422306 ; 13 : 9 _g 41 up 28
lf 343 0 256 -7 1 64 1 128 1.4612164 64 1.4612164 ; 19 : 13 _g 42 up 29
lf 344 0 256 -7 1 64 1 128 1.4804520 64 1.4804520 ; 37 : 25 _g 43 up 30
lf 345 0 256 -7 1 64 1 128 1.4999409 64 1.4999409 ; 3 : 2 _g 44 up 31
lf 346 0 256 -7 1 64 1 128 1.5196863 64 1.5196863 ; 38 : 25 _g 45 up 32
lf 347 0 256 -7 1 64 1 128 1.5396917 64 1.5396917 ; 20 : 13 _g 46 up 33
lf 348 0 256 -7 1 64 1 128 1.5599604 64 1.5599604 ; 39 : 25 _g 47 up 34
lf 349 0 256 -7 1 64 1 128 1.5804960 64 1.5804960 ; 30 : 19 _g 48 up 35
lf 350 0 256 -7 1 64 1 128 1.6013018 64 1.6013018 ; 8 : 5 _g 49 up 36
lf 351 0 256 -7 1 64 1 128 1.6223816 64 1.6223816 ; 13 : 8 _g 50 up 37
lf 352 0 256 -7 1 64 1 128 1.6437389 64 1.6437389 ; 23 : 14 _g 51 up 38
lf 353 0 256 -7 1 64 1 128 1.6653773 64 1.6653773 ; 5 : 3 _g 52 up 39
lf 354 0 256 -7 1 64 1 128 1.6873006 64 1.6873006 ; 27 : 16 _g 53 up 40
lf 355 0 256 -7 1 64 1 128 1.7095124 64 1.7095124 ; 12 : 7 _g 54 up 41
lf 356 0 256 -7 1 64 1 128 1.7320167 64 1.7320167 ; 26 : 15 _g 55 up 42
lf 357 0 256 -7 1 64 1 128 1.7548172 64 1.7548172 ; 7 : 4 _g 56 up 43
lf 358 0 256 -7 1 64 1 128 1.7779179 64 1.7779179 ; 16 : 9 _g 57 up 44
lf 359 0 256 -7 1 64 1 128 1.8013226 64 1.8013226 ; 9 : 5 _g 58 up 45
lf 360 0 256 -7 1 64 1 128 1.8250355 64 1.8250355 ; 42 : 23 _g 59 up 46
lf 361 0 256 -7 1 64 1 128 1.8490605 64 1.8490605 ; 37 : 20 _g 60 up 47
lf 362 0 256 -7 1 64 1 128 1.8734018 64 1.8734018 ; 15 : 8 _g 61 up 48
lf 363 0 256 -7 1 64 1 128 1.8980636 64 1.8980636 ; 19 : 10 _g 62 up 49
lf 364 0 256 -7 1 64 1 128 1.9230499 64 1.9230499 ; 25 : 13 _g 63 up 50
lf 365 0 256 -7 1 64 1 128 1.9483652 64 1.9483652 ; 37 : 19 _g 64 up 51
lf 366 0 256 -7 1 64 1 128 1.9740138 64 1.9740138 ; 75 : 38 _g 65 up 52
lf 367 0 256 -7 1 64 1 128 2.0000000 64 2.0000000 ; 2 : 1 _g 66 up 53
lf 368 0 256 -7 1 64 1 128 0.9870069 64 0.9870069 ; 76 : 77 _g 67 down 1
lf 369 0 256 -7 1 64 1 128 0.9741826 64 0.9741826 ; 38 : 39 _g 68 down 2
lf 370 0 256 -7 1 64 1 128 0.9615250 64 0.9615250 ; 25 : 26 _g 69 down 3
lf 371 0 256 -7 1 64 1 128 0.9490318 64 0.9490318 ; 19 : 20 _g 70 down 4
lf 372 0 256 -7 1 64 1 128 0.9367009 64 0.9367009 ; 15 : 16 _g 71 down 5
lf 373 0 256 -7 1 64 1 128 0.9245303 64 0.9245303 ; 12 : 13 _g 72 down 6
lf 374 0 256 -7 1 64 1 128 0.9125178 64 0.9125178 ; 10 : 11 _g 73 down 7
lf 375 0 256 -7 1 64 1 128 0.9006613 64 0.9006613 ; 9 : 10 _g 74 down 8
lf 376 0 256 -7 1 64 1 128 0.8889589 64 0.8889589 ; 8 : 9 _g 75 down 9
lf 377 0 256 -7 1 64 1 128 0.8774086 64 0.8774086 ; 7 : 8 _g 76 down 10
lf 378 0 256 -7 1 64 1 128 0.8660083 64 0.8660083 ; 13 : 15 _g 77 down 11
lf 379 0 256 -7 1 64 1 128 0.8547562 64 0.8547562 ; 6 : 7 _g 78 down 12
lf 380 0 256 -7 1 64 1 128 0.8436503 64 0.8436503 ; 16 : 19 _g 79 down 13
lf 381 0 256 -7 1 64 1 128 0.8326886 64 0.8326886 ; 5 : 6 _g 80 down 14
lf 382 0 256 -7 1 64 1 128 0.8218694 64 0.8218694 ; 23 : 28 _g 81 down 15
lf 383 0 256 -7 1 64 1 128 0.8111908 64 0.8111908 ; 13 : 16 _g 82 down 16
lf 384 0 256 -7 1 64 1 128 0.8006509 64 0.8006509 ; 4 : 5 _g 83 down 17
lf 385 0 256 -7 1 64 1 128 0.7902480 64 0.7902480 ; 15 : 19 _g 84 down 18
lf 386 0 256 -7 1 64 1 128 0.7799802 64 0.7799802 ; 7 : 9 _g 85 down 19
lf 387 0 256 -7 1 64 1 128 0.7698459 64 0.7698459 ; 10 : 13 _g 86 down 20
lf 388 0 256 -7 1 64 1 128 0.7598432 64 0.7598432 ; 19 : 25 _g 87 down 21
lf 389 0 256 -7 1 64 1 128 0.7499705 64 0.7499705 ; 3 : 4 _g 88 down 22
lf 390 0 256 -7 1 64 1 128 0.7402260 64 0.7402260 ; 20 : 27 _g 89 down 23
lf 391 0 256 -7 1 64 1 128 0.7306082 64 0.7306082 ; 19 : 26 _g 90 down 24
lf 392 0 256 -7 1 64 1 128 0.7211153 64 0.7211153 ; 8 : 11 _g 91 down 25
lf 393 0 256 -7 1 64 1 128 0.7117458 64 0.7117458 ; 42 : 59 _g 92 down 26
lf 394 0 256 -7 1 64 1 128 0.7024980 64 0.7024980 ; 7 : 10 _g 93 down 27
lf 395 0 256 -7 1 64 1 128 0.6933704 64 0.6933704 ; 9 : 13 _g 94 down 28
lf 396 0 256 -7 1 64 1 128 0.6843613 64 0.6843613 ; 13 : 19 _g 95 down 29
lf 397 0 256 -7 1 64 1 128 0.6754694 64 0.6754694 ; 25 : 37 _g 96 down 30
lf 398 0 256 -7 1 64 1 128 0.6666929 64 0.6666929 ; 2 : 3 _g 97 down 31
lf 399 0 256 -7 1 64 1 128 0.6580305 64 0.6580305 ; 25 : 38 _g 98 down 32
lf 400 0 256 -7 1 64 1 128 0.6494807 64 0.6494807 ; 13 : 20 _g 99 down 33
lf 401 0 256 -7 1 64 1 128 0.6410419 64 0.6410419 ; 25 : 39 _g 100 down 34
lf 402 0 256 -7 1 64 1 128 0.6327128 64 0.6327128 ; 19 : 30 _g 101 down 35
lf 403 0 256 -7 1 64 1 128 0.6244919 64 0.6244919 ; 5 : 8 _g 102 down 36
lf 404 0 256 -7 1 64 1 128 0.6163778 64 0.6163778 ; 8 : 13 _g 103 down 37
lf 405 0 256 -7 1 64 1 128 0.6083691 64 0.6083691 ; 14 : 23 _g 104 down 38
lf 406 0 256 -7 1 64 1 128 0.6004645 64 0.6004645 ; 3 : 5 _g 105 down 39
lf 407 0 256 -7 1 64 1 128 0.5926626 64 0.5926626 ; 16 : 27 _g 106 down 40
lf 408 0 256 -7 1 64 1 128 0.5849621 64 0.5849621 ; 7 : 12 _g 107 down 41
lf 409 0 256 -7 1 64 1 128 0.5773616 64 0.5773616 ; 15 : 26 _g 108 down 42
lf 410 0 256 -7 1 64 1 128 0.5698599 64 0.5698599 ; 4 : 7 _g 109 down 43
lf 411 0 256 -7 1 64 1 128 0.5624557 64 0.5624557 ; 9 : 16 _g 110 down 44
lf 412 0 256 -7 1 64 1 128 0.5551476 64 0.5551476 ; 5 : 9 _g 111 down 45
lf 413 0 256 -7 1 64 1 128 0.5479345 64 0.5479345 ; 23 : 42 _g 112 down 46
lf 414 0 256 -7 1 64 1 128 0.5408152 64 0.5408152 ; 20 : 37 _g 113 down 47
lf 415 0 256 -7 1 64 1 128 0.5337883 64 0.5337883 ; 8 : 15 _g 114 down 48
lf 416 0 256 -7 1 64 1 128 0.5268527 64 0.5268527 ; 10 : 19 _g 115 down 49
lf 417 0 256 -7 1 64 1 128 0.5200073 64 0.5200073 ; 13 : 25 _g 116 down 50
lf 418 0 256 -7 1 64 1 128 0.5132508 64 0.5132508 ; 19 : 37 _g 117 down 51
lf 419 0 256 -7 1 64 1 128 0.5065821 64 0.5065821 ; 38 : 75 _g 118 down 52
lf 420 0 256 -7 1 64 1 128 0.5000000 64 0.5000000 ; 1 : 2 _g 119 down 53
@ trills
lf 421 0 256 -7 1 16 1 0 1.1249114 16 1.1249114 0 1 16 1 0 1.1249114 16 1.1249114
l 0 1 16 1 0 1.124911356 16 1.124911356 0 1 16 1 0 1.124911356 16 1.124911356
l 0 1 16 1 0 1.124911356 16 1.124911356 0 1 16 1 0 1.124911356 16 1.124911356
l 0 1 16 1 0 1.124911356 16 1.124911356 0 1 16 1 0 1.124911356 16 1.124911356 ; 9 : 8 120 up & down 9
lf 422 0 256 -7 1 16 1 0 1.1102953 16 1.1102953 0 1 16 1 0 1.1102953 16 1.1102953
l 0 1 16 1 0 1.110295271 16 1.110295271 0 1 16 1 0 1.110295271 16 1.110295271
l 0 1 16 1 0 1.110295271 16 1.110295271 0 1 16 1 0 1.110295271 16 1.110295271
l 0 1 16 1 0 1.110295271 16 1.110295271 0 1 16 1 0 1.110295271 16 1.110295271 ; 11 : 10 121 up & down 8
lf 423 0 256 -7 1 16 1 0 1.1699242 16 1.1699242 0 1 16 1 0 1.1699242 16 1.1699242
l 0 1 16 1 0 1.169924228 16 1.169924228 0 1 16 1 0 1.169924228 16 1.169924228
l 0 1 16 1 0 1.169924228 16 1.169924228 0 1 16 1 0 1.169924228 16 1.169924228
l 0 1 16 1 0 1.169924228 16 1.169924228 0 1 16 1 0 1.169924228 16 1.169924228 ; 7 : 6 122 up & down 12
lf 424 0 256 -7 1 16 1 0 1.0958691 16 1.0958691 0 1 16 1 0 1.0958691 16 1.0958691
l 0 1 16 1 0 1.095869093 16 1.095869093 0 1 16 1 0 1.095869093 16 1.095869093
l 0 1 16 1 0 1.095869093 16 1.095869093 0 1 16 1 0 1.095869093 16 1.095869093
l 0 1 16 1 0 1.095869093 16 1.095869093 0 1 16 1 0 1.095869093 16 1.095869093 ; 12 : 11 123 up & down 7
lf 425 0 256 -7 1 16 1 0 1.0675766 16 1.0675766 0 1 16 1 0 1.0675766 16 1.0675766
l 0 1 16 1 0 1.067576625 16 1.067576625 0 1 16 1 0 1.067576625 16 1.067576625
l 0 1 16 1 0 1.067576625 16 1.067576625 0 1 16 1 0 1.067576625 16 1.067576625
l 0 1 16 1 0 1.067576625 16 1.067576625 0 1 16 1 0 1.067576625 16 1.067576625 ; 16 : 15 124 up & down 5
lf 426 0 256 -7 1 16 1 0 1.1102953 16 1.1102953 0 1 16 1 0 1.1102953 16 1.1102953
l 0 1 16 1 0 1.110295271 16 1.110295271 0 1 16 1 0 1.110295271 16 1.110295271
l 0 1 16 1 0 1.110295271 16 1.110295271 0 1 16 1 0 1.110295271 16 1.110295271
l 0 1 16 1 0 1.110295271 16 1.110295271 0 1 16 1 0 1.110295271 16 1.110295271 ; 10 : 9 125 up & down 8
lf 427 0 256 -7 1 16 1 0 1.0816304 16 1.0816304 0 1 16 1 0 1.0816304 16 1.0816304
l 0 1 16 1 0 1.081630356 16 1.081630356 0 1 16 1 0 1.081630356 16 1.081630356
l 0 1 16 1 0 1.081630356 16 1.081630356 0 1 16 1 0 1.081630356 16 1.081630356
l 0 1 16 1 0 1.081630356 16 1.081630356 0 1 16 1 0 1.081630356 16 1.081630356 ; 14 : 13 126 up & down 6
; Glides optimized for 53 tone stepsize:                                                                                 1.0131641               0.9870069
l; Glissando from key to key some unique ratios. Now we're talking microtonal.
@ end of glissandi
l;   Envelopes
l; autoscale all following tables to 1
l;#7  0 siz
l;#6  0 siz exp min values mid val  max   vals mid vals min val mid val max
lf298 0 1025 6  0     1     .5  1   1     496  1   496  1    15 .5   15 0.0 ; e0 - Attack and sustain with a relatively sharp ending
;lf297 0 1025 6  0     1     .5  1   1     496  1   496  1    15 .5   15 0.0 ; e1 - Attack and sustain with a relatively sharp ending
lf297 0 1025 6  0     3     .5  3   1     494  1   494  1    15 .5   15 0.0 ; e1 - Attack and sustain with a relatively sharp ending
l;#5 0 siz exp start take reach take reach
lf296 0 513  5  1024 512     1                                     ; e2 - exponential - dead piano
l;#6  0 siz exp min values mid val max val mid val  min val mid val max val mid val min
lf295 0 129  6  0     8    .5   8   1  16  .6  16   .3  16  .5  16  .6   24 .3   24  0 ; e3  big hump, small hump
lf294 0 129  6  0     8    .15  8  .3  16  .25 16   .2  16  .6  16  1    24 .5   24  0 ; e4  small hump, big hump
lf293 0 1025 6  0     1    .5   1   1  447 .99 447 .98  64 0.5  64  0 ;e5 default woodwind envelope
lf292  0 1025 6 0   1   0.50 1   1.00  447  0.60 447 0.20 32   0.21 32  0.22 32  0.11 32  0.00 ; e6 channel one moving away slowly
lf291  0 1025 6 0   1   0.50 1   1.00  128   0.60 128  0.20 256   0.15 254  0.10 128  0.05 128  0.00 ; e7 channel one moving away faster
lf290 0 1025 6  0     1    .5   1   1  503 .6  483 .3   18   .15 18  0 ; e8  hit and drop most
lf289 0 1025 6  0     1    .3   1  .6  479 .8  479  1   32  .5  32 0 ; e9  Start moderately and build, abrupt end
lf288 0 1025 6  .10  256   .40 256  1  256 .6  256  0                ; e10  One hump in the middle
lf287 0 1025 6  0     1    .5   1   1  368 .99 368 .98  16 .5 16 0 127 0 127 0 ; e11  hit and sustain 3/4 the normal length
lf286 0 1025 6  0     1    .5   1   1  303 .99 303 .98  16 .5 16 0 192 0 192 0 ; e12  hit and sustain 2/3 the normal length
lf285 0 1025 6  0     1    .5   1   1  255 .99 255 .98  16 .5 16 0 240 0 240 0 ; e13  hit and sustain 1/2 the normal length
lf284 0 1025 6  0     1    .5   1   1  192 .99 192 .98  16 .5 16 0 303 0 303 0 ; e14  hit and sustain 1/3 the normal length
lf283 0 1025 6  0    384   .5  384  1   128 .5  128  0                ; e15  one hump towards the end
lf282 0 1025 6  0     1    .2   1  .4  479 .7  479  1   32  .5  32 0 ; e16  sustain piano sound
lf281 0 1025 6  0     1    .1   1  .2  479 .6  479  1   32  .5  32 0 ; e17  sustain guitar sound
lf280 0 1025 6  1  64  .7  64  .4 64  .4 64  .4 384 .7  352  1 16 .5 16 0  ; e18  Sharp attack, then less quiet, build to end
lf279 0 1025 6  0  1 .5  1  1.0 128  .7 228  .4 128 .4  28 .4 128 .5  128 .6 128 .3 126 0  ; e19  Moderate attack, then slightly quiet, build to end
@      85   170  255  340  425  510  595  680  765  850  935  1024
lf278 0 1025 6 0 85 0.40 85 0.80 85 0.65 85 0.50 85 0.75 85 1.00 85 0.75 85 0.50 85 0.65 85 0.8 85 0.4 89 0.0 ; e20 3 humps - biggest in middle
lf277 0 1025 6 0 85 0.50 85 1.00 85 0.75 85 0.50 85 0.65 85 0.80 85 0.65 85 0.50 85 0.65 85 0.8 85 0.4 89 0.0 ; e21 3 humps - biggest early
lf276 0 1025 6 0 85 0.40 85 0.80 85 0.65 85 0.50 85 0.65 85 0.80 85 0.65 85 0.50 85 0.75 85 1.0 85 0.5 89 0.0 ; e22 3 humps - biggest late
@ 1 85 169 253 337 421 505 589 673 757 841 1024
lf275 0 1025 6 0 1 0.20 84 0.80 84 0.65 84 0.50 84 0.75 84 1.00 84 0.75 84 0.50 84 0.65 84 0.8 84 0.4 183 0.0 ; e23 3 humps - early biggest in middle
lf274 0 1025 6 0 1 0.20 84 1.00 84 0.75 84 0.50 84 0.65 84 0.80 84 0.65 84 0.50 84 0.65 84 0.8 84 0.4 183 0.0 ; e24 3 humps - early biggest early
lf273 0 1025 6 0 1 0.20 84 0.80 84 0.65 84 0.50 84 0.65 84 0.80 84 0.65 84 0.50 84 0.75 84 1.0 84 0.5 183 0.0 ; e25 3 humps - early biggest late
;               min pts mid  pts max   pts  mid  pts min  pts  mid  pts max  pts mid  pts min
;p1    2 3    4 5   6   7    8   9     10   11   12  13   14   15   16  17   18  19   20  21   ;
lf265  0 1025 6 0   32  0.20 32  0.40  32   0.30 32  0.20 432  0.60 432 1.00 16  0.50 16  0.00 ; e33 channel one moving in gradually
lf264  0 1025 6 0   206 0.03 206 0.06  205  0.06 205 0.05 85   0.53 85  1.00 16  0.50 16  0.00 ; e34 channel 2 moving in at the end
@ just the last four chords - half the function
@ humps:                  1                          2                          3                          4
@ troughs     0                         1                          2                          3
@ humps                     5                          6                          7                          8
@ troughs     4                          5                          6                          7                         8
lf263 0 513 6 0 16 .5 16 1.0 32 .55 32 .1 32 .55 32 1.0 32 .55 32 .1 32 .55 32 1.0 32 .55 32 .1 32 .55 32 1.0 48 .5 48 0 ; e35 flu
lf262 0 513 6 0 16 .5 16 1.0 32 .55 32 .1 32 .55 32 1.0 32 .55 32 .1 32 .55 32 1.0 32 .55 32 .1 32 .55 32 1.0 48 .5 48 0 ; e36 obo
lf261 0 513 6 0 16 .5 16 1.0 32 .55 32 .1 32 .55 32 1.0 32 .55 32 .1 32 .55 32 1.0 32 .55 32 .1 32 .55 32 1.0 48 .5 48 0 ; e37 frn
lf260 0 513 6 0 16 .5 16 1.0 32 .55 32 .1 32 .55 32 1.0 32 .55 32 .1 32 .55 32 1.0 32 .55 32 .1 32 .55 32 1.0 48 .5 48 0 ; e38 bas
lf259 0 513 6 0 16 .2 16  .4 32 .2  32 .1 32 .15 32  .2 32 .15 32 .1 32 .60 32 1.0 32 .60 32 .2 32 .30 32  .4 48 .2 48 0 ; e39 cla
lf258 0 513 6 0 16 .2 16  .4 32 .2  32 .1 32 .15 32  .2 32 .15 32 .1 32 .60 32 1.0 32 .60 32 .2 32 .30 32  .4 48 .2 48 0 ; e40 cla
lf257 0 513 6 0 16 .2 16  .4 32 .2  32 .1 32 .15 32  .2 32 .15 32 .1 32 .60 32 1.0 32 .60 32 .2 32 .30 32  .4 48 .2 48 0 ; e41 cla
@  sawtooth tempos - gradually increase and then suddenly decrease tempo, then do it again
l; start at time 0
l; | with tempo = 480  beats per minute
l; | |   same tempo through time 404
l; | |   |   tempo at end of this time period
l; | |   |   |   starting at this time
l; | |   |   |    |  change to tempo 540 beats per minute
l; | |   |   |    |  |   Stay at that tempo through time 808
l; | |   |   |    |  |   |   tempo at end of this time period
l; | |   |   |    |  |   |   |   at this time start a new tempo of 600
l; | |   |   |    |  |   |   |   |   tempo at new time
l; | |   |   |    |  |   |   |   |       stay there until time 1271
@lt0 480 404 480 405 540 808 540 809 600 1271 600 1272 540 2871 540 2872 360
l;                t16       t16       t17        t17        t18        t19        t20        t21        t22        t23
l; 218
l; / 24     1    16
@lt 0 750
@lt 0 500 1500 540 2800 480 3000 780
@ higher the number the faster the tempo
@ tempo
lt 0 1894
f; This is the post processor that takes as input a function table with volume points and alters the overall volume
f<CsoundSynthesizer>
f<CsOptions>
f-W -G -m2 -+y -o sflib\sing53a.wav
f</CsOptions>
f
f<CsInstruments>
f sr = 44100
f ksmps = 2 ; any higher than 10 and I hear clicks - use 1 for final take
f; typically save 5x processing time by increasing ksmps by 10x
f nchnls = 2
f
f instr 99
f   kamp poscil 1, 1/p3, 1 ; create a set of volume points from a function table that lasts as long as the input file
f   a6, a7 soundin "sflib/sing53.wav"
f   outs a6 * kamp, a7 * kamp
f endin
f</CsInstruments>
f
f<CsScore>
f; go from 1 to 0 over 1024 points - overall amplitude for crescendo and decresendo purposes
f; This needs to be customized with specific points on the way.
f;
f;
ft 0 1894
@ also change lt 0 1894
@1.31641%        2000    1973.671714
@2.63283%        2000    1947.343428
@3.94924%        2000    1921.015142
@5.26566%        2000    1894.686856
@6.58207%        2000    1868.35857
@7.89849%        2000    1842.030284
@9.21490%        2000    1815.701998
@10.53131%       2000    1789.373712
@11.84773%       2000    1763.045426
@ note names using Sagittal font locations
@ What should I call them? by ratio for now:
@ if this gets bigger than 59, need to modify the samples.pas program to update the "root" variable.
@
@ McGill University Master Sample Set
@
@ Instruments available
@
@ 2 HARP-HARMONC     3 HARP            4 HARPSIC-STOP   5 HARPSI-4 FT      6 HARPSI-4+8FT  7 HARPSI-8 FT
@ 8 MARIMBA          9 OBOE-BAROQUE   10 OBOE          11 PIPES-CORNET    12 PIPES-fLUTE  13 PIPE-PEDALS
@14 PIPES-PLENUM    16 PIPES-PRINZ    17 PIPES-REEDS   20 GRAND PIANO FF 107 GRAND PIANO MF
@21 PEDAL PIANO FF 107 PEDAL PIANO MF 23 PIANO HARMON  24 PLUCKEDPIANO    25 PICCOLO W-VB
@26 PICCOLO         27 RECRDER-ALTO   28 RECRDER-BARQ  29 SOP.BRQ.RDRQ    30 BASSINETT    31 BASS RECORDR
@32 RECRDR-QUART    33 SOPRANO RCRD   34 SHAWM-ALTO    35 TROMBONE-BS     36 TROMBONE-MTD 37 TROMBONE-ALT
@38 TROMBONE-TNR    39 TRUMPET-BACH?? 40 TRUMPET-C     41 TUBA            42 TUBULAR BELL 43 TYMPANI-HARD
@45 TYMPANI-SOFT    46 TYMPANI-WOOD   47 VIBRAPHONE    48 BASS VIOL       49 TREBLE VIOL  50 VIOLA-BOWED
@51 VIOLA-MARTEL    52 VIOLA-PIZZ     53 VIOLA W-VIB   54 VIOLIN-BOWnovib 55 VIOLIN-HARM  56 VIOLIN-MART
@57 VIOLIN-PIZZ     58 VIOLIN W-VIB   60 VIOLIN ENSM   61 VIOL.ENS.HRM    62 VIOL.ENS.MRT 63 VIOL.ENS.PIZ
@65 XYLOPHONE       66 Piano MF       67 Piano FF      68 Oberheim        70 ARCHLUTE     71 BASSOON
@72 CELESTA         73 CELLOMARTELE   74 CELLO PIZZ    75 CELLO W-VIB     76 BS. CLARINET 77 B- CLARINET
@78 E- CLARINET     79 C. CLARINET    80 CLASS.GTR.HM  81 PONTICEL.GTR    82 SULTASTO GTR 83 CLASS.GUITAR
@84 CONTf.BASSOON   85 TRBL.CORNETT   87 CROTALES      88 CRUMHORNS       90 DBL.BS.MRTLE 91 DB.BASS PIZZ
@92 DOUBLE BASS     93 ENGLISH HORN   94 A.FLUTE W-VB  95 ALTO FLUTE      96 B.FLUTE W-VB 97 BASS FLUTE
@98 FLUTTERFLUTE    99 FLUTE W-VIB   100 FLUTE NO-VIB 101 FR.HORN-MUTE   102 FRENCH HORN 103 GLOCKENSPIEL
@104 gongs
@ dry spring
n2m130
n4m131
@ bass flute 96
n1m96
@ cello martele
n3m73
@ finger piano
n5m112
@n6m128
@n7m127
@n8m127
@n9m129
@ finger piano
n10m112
n14m112
@ balloon drum
n11m116
@ this instrument never sounds. It is just there to keep track of overall volume for crescendo and decrescendo purposes
n12m2
n15m98
@
@
@ 89 Cymbals - very orchestra-y - boring
@ o5t0 thru o5t3
@.20INCHINA  o5t0
@ o5t4 thru 06t4
@.ORCHCRASH  o5t4
@ 64 waterphone
@.WATERPHIT o6t0
@.WATERPHON o6t4
@ 104 GONGS - very good
.gongl t0o5
.gongm t0o6
.gongs t0o7
.gong1 o7t12
.gong2 o7t41
.gong3 o8t12
.gong4 o8t41
.gong5 o9t12
@ 18 percussion - just the cowbell this time
@   .cuica-low t32o3
@   .alpglock1 t36o3
@   .brakdrum1 t41o3
@   .cabasahit t47o3
@   .casnt-hit t51o3
@.agogo1   t54o3
@   .cuicamdlo t3o4
@   .chinagon1 t8o4
@   .alpglock2 t12o4
@   .bamboochm t18o4
@   .cuicamdhi t21o4
@.agogo2   t28o4
@   .cencerro1 t32o4
@   .brakdrum2 t36o4
@   .cabasarol t41o4
@   .castntrll t46o4
@   .claves    t51o4
@   .fingrcymb t54o4
@   .icebells  t2o5
@   .cencerros t8o5
@   .cencrros3 t14o5
@   .cuica-hi1 t18o5
@   .alpglock3 t22o5
@   .alpglock4 t27o5
@   .chingong2 t33o5
@   .rattle1   t36o5
@   .cuicaslid t44o5
@ need to make different versions of these, starting and ending at a different point in the sample
@ restaurant sounds - not used
@   .glassb1 o2t37
@   .glassb2 o3t25
@   .glassb3 o4t2
@   .glaswep o5t2
@   .resttalk o5t27
@   .resteleg o6t0
@   .laugh1 o6t23
@   .laugh2 o7t13
@   .ohh o7t23
@   .ahh o8t10
@   .polite1 o9t0
@   .polite2 o9t20
@   .polite3 o10t0
@ 110 Mwave samples 44 kHz
@.cymb-1 o3t34
@.cymb-2 o3t40
@.hhclo o3t46
@.hhfot o3t50
@.hhopn o3t53
@.tom-h1 o4t3
@.tom-h2 o4t7
@.kick1 o4t11h7
@.kick2 o4t17h4
@.tom-l1 o4t21
@.tom-l2 o4t25
@.ride1 o4t30
@.ride2 o4t35
@.snar-1 o4t39
@.snar-2 o4t44
@.splas o4t49
@.tamb1 o4t55
@.timbh o5t2
@.timbl o5t7
@.tom-m1 o5t13
@.tom-m2 o5t17
@.bongh o5t21
@.guirs o5t26
@.guirf o5t31
@.congs o5t36
@.congl o5t39
@.congh o5t44
@.clave o5t50
@.claps o5t54
@.cabas o6t1
@.bongl o6t6
@.marac o6t12
@ 89
.15TURKCRAS1 o4t50
.15TURKCRAS2 o4t54
.15TURKCRAS3 o5t1
.15TURKSOFT o5t6
@ 117 Spring bangs
.spring1 o3t16
.spring2 o3t31
.spring3 o3t36
.spring4 o3t41
.spring4a o3t46
.spring5 o3t51
.spring6 o3t56
.spring7 o4t4
@ how many steps in the scale
@  1   2    3    4     5     6     7     8     1
@ 1:1 9:8  5:4 11:8   3:2  13:8   7:4  15:8   2:1
@  0   9    8    8     6     6     6     5     5
@ 1:1 9:8 10:9 11:10 12:11 13:12 14:13 15:14 16:15
@ staight glide, no vibrato, steady change from opening to ending
.gls77:76 g14
.gls39:38 g15
.gls26:25 g16
.gls20:19 g17
.gls16:15 g18
.gls13:12 g19
.gls12:11 g20
.gls11:10 g21
.gls10:9 g21
.gls9:8 g22
.gls8:7 g23
.gls15:13 g24
.gls7:6 g25
.gls19:16 g26
.gls6:5 g27
.gls28:23 g28
.gls16:13 g29
.gls5:4 g30
.gls19:15 g31
.gls9:7 g32
.gls13:10 g33
.gls25:19 g34
.gls4:3 g35
.gls27:20 g36
.gls26:19 g37
.gls11:8 g38
.gls59:42 g39
.gls10:7 g40
.gls13:9 g41
.gls19:13 g42
.gls37:25 g43
.gls3:2 g44
.gls38:25 g45
.gls20:13 g46
.gls39:25 g47
.gls30:19 g48
.gls8:5 g49
.gls13:8 g50
.gls23:14 g51
.gls5:3 g52
.gls27:16 g53
.gls12:7 g54
.gls26:15 g55
.gls7:4 g56
.gls16:9 g57
.gls9:5 g58
.gls42:23 g59
.gls24:13 g60
.gls15:8 g61
.gls19:10 g62
.gls25:13 g63
.gls37:19 g64
.gls75:38 g65
.gls2:1 g66
.gls76:77 g67
.gls38:39 g68
.gls25:26 g69
.gls19:20 g70
.gls15:16 g71
.gls12:13 g72
.gls11:12 g73
.gls9:10 g74
.gls8:9 g75
.gls7:8 g76
.gls13:15 g77
.gls6:7 g78
.gls16:19 g79
.gls5:6 g80
.gls23:28 g81
.gls13:16 g82
.gls4:5 g83
.gls15:19 g84
.gls7:9 g85
.gls10:13 g86
.gls19:25 g87
.gls3:4 g88
.gls20:27 g89
.gls19:26 g90
.gls8:11 g91
.gls42:59 g92
.gls7:10 g93
.gls9:13 g94
.gls13:19 g95
.gls25:37 g96
.gls2:3 g97
.gls25:38 g98
.gls13:20 g99
.gls25:39 g100
.gls19:30 g101
.gls5:8 g102
.gls8:13 g103
.gls14:23 g104
.gls3:5 g105
.gls16:27 g106
.gls7:12 g107
.gls15:26 g108
.gls4:7 g109
.gls9:16 g110
.gls5:9 g111
.gls23:42 g112
.gls13:24 g113
.gls8:15 g114
.gls10:19 g115
.gls13:25 g116
.gls19:37 g117
.gls38:75 g118
.gls1:2 g119
@ trills
@ 16:15 is 5 steps
@ 15:14 is 5 steps
@ 14:13 is 6 steps
@ 12:11 is 7 steps
@ 11:10 is 8 steps
@ 9:8 is 9 steps
@ 10:9 is 8 steps
@ 7:6 is 12 steps
.trl9:8 g120
.trl11:10 g121
.trl7:6 g122
.trl12:11 g123
.trl16:15 g124
.trl15:14 g124
.trl10:9 g125
.trl14:13 g126
@cvdhotrsepgzu
@.side-2 s2
.side-4 s4
.side-6 s6
.side-8 s8
.side-10 s10
.side-12 s12
@.side-14 s14
.flu-sid-6 s6
.flu-sid-8 s8
.flu-sid-10 s10
@ Tonality Diamond
@                         F++
@                     D+      D-
@                 A++     Bb      B-
@             G       F#      G       G#
@         E       E--     D#      E++     E-
@     C       C       C       C       C       C
@         Ab      A-      A+      G++     A--
@             F       Gb      F       E+
@                 D++     D       D--
@                     A#      B--
@                         G--
@
@ u3 = most mellow
@ u2 = more mellow
@ u1 = a little more mellow
@ u0 = normal sample
@ u255 = take a sample designed for a lower note and use it for a higher note - munchkinize it
@ u254 = very nasal
@ u253 = Most nasal
@
@
@ initialize each
@ these total to 144
@   .dur1 d12h10
@   .dur2 d36h38
@   .dur3 d12h10
@   .dur4 d36h38
@   .dur5 d24h10
@   .dur6 d24h10
@   .slidur d96h100
@
@.all-z0 z0
.all-z1 z1
.all-z2 z2
.all-z3 z3
.all-z4 z4
.all-z5 z10
.per-z0 &all-z*.
.all-sid1a s1
.all-sid1b s4
.all-sid1c s6
.all-sid4a s4
.all-sid4b s6
.all-sid4c s8
.all-sid6a s6
.all-sid6b s8
.all-sid6c s10
.all-sid8a s23
.all-sid10a s6
.all-sid10b s8
.all-sid10c s10
.all-sid12a s8
.all-sid12b s10
.all-sid12c s12
.all-sid15a s10
.all-sid15b s12
.all-sid15c s15
@
@ extent of repeatability:
@   p16 - lots of repeats, but gradually changes
@   p25 - almost always the same thing
@   p32 - same always.
@   p33 - step through the alternatives one by one forward
@   p34 - step through the alternatives one by one backward
@   p8 - random choice
@   p1 - random choice but try to pick something else first
@.tru-oct-4a o4u1
.tr1-oct-4b o3u0
.tr2-oct-4b o3u0
.hor-oct-3a o5u0
.tro-oct-2a o2u0
.tub-oct-1a o3u0
@ who choses the riff?
@
.fin-oct-1a o3u0
@.fi2-oct-1a o3u2
.fi2-oct-3a o3u1
.fi2-oct-3b o3u0
.fi2-oct-3c o3u255
.fi3-oct-3a o3u1
.fi3-oct-3b o3u0
.fi3-oct-3c o3u255
.fi3-oct-4a o4u255
.fi3-oct-4b o4u0
.fin-env e5
.fin-z1 z0
.flu-oct-5a o5u0
.cel-oct-3a o3u0
.flu-ran-1 r16
.fin-ran-1 r16
.cel-ran-1 r16
.ce2-ran-1 r12
.flu-pva-1 p33
.fl2-pva-1 p33
.har-pva-1 p33
.fin-pva-1 p33
.dsp-pva-1 p33
.cel-pva-1 p33
@
.fl2-vel2 &all-vel*.v-4
.fin-vel2 &all-vel*.v-2
.cel-vel1 &all-vel*.v-2
.flu-vel1 &all-vel*.v+2
.dsp-vel &all-vel*.
@ durations and holds for articulation variation
.tim-hol12 h12
.tim-hol10 h10
.tim-hol8  h8
.tim-hol6  h6
.tim-hol4  h4
.hol4-a h3
.hol4-b h4
.hol4-c h5
.hol6-a h4
.hol6-b h5
.hol6-c h6
.hol8-a h6
.hol8-b h8
.hol8-c h10
.hol12-a h10
.hol12-b h12
.hol12-c h14
.hol16-a h14
.hol16-b h16
.hol16-c h18
.shift-l s8e22w15
.shift-r s8e15w22
@.upsamp0 g0
@.upsamp1 g1
.upsamp2 g2
.upsamp3 g3
.upsamp4 g4
@.upsamp5 g5
.flu c1a0w0&flu-vel*.&flu-sid*.e1g0h0z0&flu-oct*.&flu-ran*.
.dsp c2a0w0&sid*.e1u0&upsamp*.h0z0&dsp-ran*.
.ds2 c4a0w0&sid*.e1u0&upsamp*.h0z0&dsp-ran*.
.cel c3a0w0&cel-vel*.&sid*.e1g0h0z0&cel-oct*.&cel-ran*.
.fib c5a0w0&fin-vel*.v+4&sid*.&fin-env.g0h0z0&fin-oct*.&fin-ran*.
.fi2 c10a0w0&fin-vel*.v-2&sid*.&fin-env.g0h0&fin-z*.&fi2-oct*.&fin-ran*.
.fi3 c14a0w0&fin-vel*.&sid*.&fin-env.g0h0z0&fi3-oct*.u0&fin-ran*.
.bal c11a0w0&bal-vel*.&sid*.e1g0h0z0&bal-oct*.&bal-ran*.
.vel c12a1w0v1s8e0g0h0z0o3t1r16
.all-vel v70
@ Closest low number just ratio to 53 tone equal temperment
@ deg n/d
@ 0 1/1
@ 1 77/76
@ 2 39/38
@ 3 26/25
@ 4 20/19
@ 5 16/15
@ 6 13/12
@ 7 11/10
@ 8 10/9
@ 9 9/8
@ 10 8/7
@ 11 15/13
@ 12 7/6
@ 13 19/16
@ 14 6/5
@ 15 28/23
@ 16 16/13
@ 17 5/4
@ 18 19/15
@ 19 9/7
@ 20 13/10
@ 21 25/19
@ 22 4/3
@ 23 27/20
@ 24 26/19
@ 25 11/8
@ 26 59/42
@ 27 10/7
@ 28 13/9
@ 29 19/13
@ 30 37/25
@ 31 3/2
@ 32 38/25
@ 33 20/13
@ 34 39/25
@ 35 30/19
@ 36 8/5
@ 37 13/8
@ 38 23/14
@ 39 5/3
@ 40 27/16
@ 41 12/7
@ 42 26/15
@ 43 7/4
@ 44 16/9
@ 45 9/5
@ 46 42/23
@ 47 37/20
@ 48 15/8
@ 49 19/10
@ 50 25/13
@ 51 37/19
@ 52 75/38
@ 53 2/1
@   C  (0 + 53)  - 17 = 36
@   Ab 36        - 14 = 22
@   F  22        - 12 = 10
@   D# (10 + 53) - 19 = 44
@   Bb 44        - 16 = 28
@   Gb 28        - 12 = 16
@   E  16        - 11 = 5
@   D  5         - 5  = 0
@   C  0
@
@    dry spring 1
@    &dsp.d8&awhee. &bark1. &bark2. &bark3. &bassdrum1. &bassdrum2. &bassdrum3. &bassdrum4.
@    &bassdrum5. &bassdrum6. &begood. &brush1. &brush2. &brush3. &brush4. &brush5. &brush6.
@    &brush7. &brush8. &chop1. &chop2. &chopchop1. &crash1. &crash2.
@    &draw1. &rock1. &rock2. &roll1.
@    dry spring 2
@    &ds2.d8
@    &scrape1. &scrape2. &scrape3. &scrape4. &scrape5.
@    &scrape6. &scrape7. &scrape8. &scrape9. &scrape10.
@    &scrape11. &scrape12. &scrape13. &scrape14. &scrape15. &scrape16. &scrape17. &scrape18.
@    &scrape19. &scrape20. &scrape21. &scrape22. &scrape23. &swirl1. &swirl2. &swirl3. &tap1. &tap2.
@    &tom1. &tom2. &cookie1. &cookie2.
@ 130 dry spring
@ give them some names after you calculate the points
.awhee o2t34&dsp-vel.v-8
.bark1 o2t37&dsp-vel.
.bark2 o2t40&dsp-vel.
.bark3 o2t46&dsp-vel.
.bassdrum1 o2t49&dsp-vel.
.bassdrum2 o3t2&dsp-vel.
.bassdrum3 o3t5&dsp-vel.
.bassdrum4 o3t11&dsp-vel.
.bassdrum5 o3t14&dsp-vel.
.bassdrum6 o3t20&dsp-vel.
.begood o3t23&dsp-vel.
.brush1 o3t29&dsp-vel.v-12
.brush2 o3t32&dsp-vel.v-12
.brush3 o3t38&dsp-vel.v-12
.brush4 o3t41&dsp-vel.v-12
.brush5 o3t47&dsp-vel.v-12
.brush6 o3t50&dsp-vel.v-12
.brush7 o4t0&dsp-vel.v-12
.brush8 o4t6&dsp-vel.v-12
.chop1 o4t9&dsp-vel.
.chop2 o4t15&dsp-vel.
.chopchop1 o4t21&dsp-vel.
.crash1 o4t32&dsp-vel.v-18
.crash2 o4t38&dsp-vel.v-20
.draw1 o4t41&dsp-vel.
.rock1 o4t47&dsp-vel.
.rock2 o4t50&dsp-vel.
.roll1 o5t0&dsp-vel.
@ need another instrument for the rest
.cookie1 o4t24&dsp-vel.v-10
.cookie2 o4t28&dsp-vel.v-10
.scrape11 o2t34&dsp-vel.v-10
.scrape12 o2t37&dsp-vel.v-10
.scrape13 o2t40&dsp-vel.v-9
.scrape14 o2t46&dsp-vel.v-9
.scrape15 o2t49&dsp-vel.v-9
.scrape16 o3t2&dsp-vel.v-9
.scrape17 o3t5&dsp-vel.v-9
.scrape18 o3t11&dsp-vel.v-9
.scrape19 o3t14&dsp-vel.v-9
.scrape20 o3t20&dsp-vel.v-9
.scrape21 o3t23&dsp-vel.v-9
.scrape22 o3t29&dsp-vel.v-9
.scrape23 o3t32&dsp-vel.v-9
.scrape1 o5t6&dsp-vel.v-9
.scrape2 o5t9&dsp-vel.v-9
.scrape3 o5t15&dsp-vel.v-9
.scrape4 o5t21&dsp-vel.v-9
.scrape5 o5t24&dsp-vel.v-9
.scrape6 o5t28&dsp-vel.v-9
.scrape7 o5t32&dsp-vel.v-9
.scrape8 o5t38&dsp-vel.v-9
.scrape9 o5t41&dsp-vel.v-9
.scrape10 o5t47&dsp-vel.v-9
.swirl1 o3t38&dsp-vel.v-0
.swirl2 o3t41&dsp-vel.v-0
.swirl3 o3t47&dsp-vel.v-0
.tap1 o3t50&dsp-vel.
.tap2 o4t0&dsp-vel.
.tom1 o4t6&dsp-vel.
.tom2 o4t11&dsp-vel.
@ subsets
.qbrush3 &brush3.
.qbrush8 &brush8.
.ds2-pva-1 p28
@ define a way to limit the scrapes to a few constant repetitions. reduce the variabilty
.dspring32-1-a &dsp.d0h4&bassd*. &qbr*. &crash1.h1d2 v-4&cra*. d0h4&bassd*.d4 d0v+4h4&dsx-r*.&bark*. &rock*. &dsp-r*.h1&cra*.d2 v-4&cra*. d0h2&crash1.d4 d0v+4h4&qbr*. &cra*.d8 d0h2&cra*.d4 d0v-4&qbr*. &chop*. &bassd*.d2 v-4&dsx-r*.
.dspring32-1-b &dsp.d0h4&bassd*. &qbr*. h2&crash1.d4 d0h4&bassd*.d4 d0h4&rock*. h1&crash1.d2 v-4d2&cra*. d0h2&cra*.d4 d0h4&qbr*. h2&cra*.d8 d0h2&cra*.d4 d0&qbr*.d2 &dsx-r*.
.dspring32-1-c &dsp.d0h4&dsx-r*.&rock*. &bassd*. h2&crash1.d4 d0h4&bassd*.d4 d0h4&bark*. h2&crash1.d4 d0h2&crash1.d4 d0h4&qbr*. h2&crash1.d8 d0h2&crash1.d4 d0&qbr*. &chop*.d2 &dsx-r*.
.dspring32-1-d &dsp.d0h16&dsp-r*.&bassd*. h2&crash1.d4 d0&bassd*.d4 d0h2&cra*.d4 d0h2&cra*.d4 d0h4&qbr*. h2&crash1.d8 d0h2&cra*.d4 d0h16&dsx-r*.&chopchop*.d4
@
.dspring32-2-a &ds2.d0&hol8*.&tom*. &dsx-ran*.&cookie*.d8 d0&scrape*.d8 &dsp-r*.d0&tap*.d4 d0&tap*.d4 &dsx-ran*.d0&scrape*.d8
.dspring32-2-b &ds2.d0&hol8*.&tom*.d8 d0&scrape*.d8 &dsp-r*.d0&hol4*.&tap*.d4 &dsx-r*.d0&tap*.d4 d0&hol8*.&scrape*.d8
.dspring32-2-c &ds2.d0&hol4*.&tom*.d16 d0&hol4*.&tap*.d16
.dspring32-2-d &ds2.d0&hol8*.&tom*. &dsx-ran*.&cookie*.d8 d0&tom*.d8 &dsp-r*.d0&hol4*.&tap*.d4 d0&tap*.d4 &dsx-ran*.d0&tom*.d8
.dspring32-2-e &ds2.d0&hol8*.&tom*.d4 s-4v-8d4 s-4v-8d4 s-4v-8d4 d0&hol4*.&tap*.d8 d0&tap*.d8
.dspring32-2-f &ds2.d4&hol8*.s-2v-1&dsx-ran*.&tom*. s-2v-1 s-2v-1 s-2v-1 s-2v-1 s-2v-1 s-2v-1 s-2v-1
@
@
@ major triads
.maj3-u-a135 t+0 t+17 t+14
.maj3-u-a351 o-1t+17 t+14 t+22
.maj3-u-a513 o-1t+31 t+22 t+17
@
.maj3-d-a531 t+31 t-14 t-17
.maj3-d-a153 t+53 t-22 t-14
.maj3-d-a315 o+1t+17 t-17 t-22
@
.maj3-u-b247 t+9 t+16 t+18
.maj3-u-b472 o-1t+25 t+18 t+19
.maj3-u-b724 o-1t+43 t+19 t+16
@
.maj3-d-b742 t+43 t-18 t-16
.maj3-d-b274 o+1t+9 t-19 t-18
.maj3-d-b427 o+1t+25 t-16 t-19
@ major fourths
@ up
.maj4-u-1 t+0 t+25 t+18
.maj4-u-2 t+9 t+22 t+22
.maj4-u-3 t+17 t+26 t+19
.maj4-u-4 t+25 t+23 t+19
.maj4-d-4 t+14 t-19 t-23
.maj4-u-5 t+31 t+22 t+25
.maj4-u-6 t+37 t+25 t+22
.maj4-u-7 t+43 t+19 t+22
.maj4-u-8 t+48 t+22 t+20
@ down
.maj4-d-1 t+43 t-18 t-25
.maj4-d-2 t+0 t-22 t-22
.maj4-d-3 t+9 t-19 t-26
.maj4-d-4 t+14 t-19 t-23
.maj4-d-5 t+25 t-25 t-22
.maj4-d-6 t+31 t-22 t-25
.maj4-d-7 t+31 t-22 t-19
.maj4-d-8 t+37 t-20 t-22
@
@ minor triads
@  utonality minor
@  1  2  3  4  5  6  7  8  0
@  0  7 14 22 31 36 41 47 53
@  0    14    31          53
@      +14   +17         +22
@     7    22       41        60
@         +15      +19       +19
.min3-u-a135 t+0 t+14 t+17
.min3-u-a351 o-1t+14 t+17 t+22
.min3-u-a513 o-1t+31 t+22 t+14
@
.min3-d-a531 o+1t+31 t-17 t-14
.min3-d-a153 o+1t+0 t-22 t-17
.min3-d-a315 t+14 t-14 t-22
@
.min3-u-b247 t+7 t+15 t+19
.min3-u-b472 o-1t+22 t+19 t+19
.min3-u-b724 o-1t+41 t+19 t+15
@
.min3-d-b742 o+1t+41 t-19 t-15
.min3-d-b274 o+1t+7  t-19 t-19
.min3-d-b427 t+22    t-15 t-19
@ minor fourths
.min4-u-1 o-1t+0 t+22 t+19
.min4-u-2 o-1t+7 t+24 t+22
.min4-u-3 o-1t+14 t+22 t+24
.min4-u-4 o-1t+22 t+19 t+19
.min4-u-5 o-1t+31 t+22 t+22
.min4-u-6 o-1t+36 t+24 t+24
.min4-u-7 o-1t+41 t+19 t+24
.min4-u-8 o-1t+47 t+20 t+22
@
.min4-d-1 t+41 t-19 t-22
.min4-d-2 o+1t+0 t-22 t-24
.min4-d-3 o+1t+7 t-24 t-22
.min4-d-4 o+1t+7 t-19 t-19
.min4-d-5 t+22 t-22 t-22
.min4-d-6 t+31 t-24 t-24
.min4-d-7 t+31 t-24 t-19
.min4-d-8 t+36 t-22 t-20
@
@ all major keys
@ ratio num 1  9  5 11  3 13  7 15  1
@ ratio den 1  8  4  8  2  8  4  8  1
@ name      C  D  E  F  G  A  B  B  C
@           1  2  3  4  5  6  7  8  1  2  3  4  5  6  7   8   1
@ absolute  0  9 17 25 31 37 43 48 53 62 70 78 84 90 96 101 106
@ steps     9  8  8  6  6  6  5  5  9  8  8  6  6  6  5   5
@ thirds a       17    14          22
@ thirds b          16       18       19
@ bass finger piano
.fib-allmaj-64-1-a &fib.&majorkey.&majoroct.d16o-1 t+31 t-31d32
.fib-allmaj-64-1-b &fib.&majorkey.&majoroct.d16o-1 o-1t+31 t+22d32h24
.fib-allmaj-64-1-c &fib.&majorkey.&majoroct.d16o-1 t+31 t-31d24 d8e8o-1t+43
@ bass slow down
.fib-allmaj-64-3-a &fib.&majorkey.&majoroct.o-1d64t+0
.fib-allmaj-64-3-b &fib.&majorkey.&majoroct.o-1d24h64t+0 d40h43o+1
.fib-allmaj-64-3-c &fib.&majorkey.&majoroct.d24t+0h64 d40h43t+31
.fib-allmaj-64-3-d &fib.&majorkey.&majoroct.o-1d24h64t+0 d40h43t+31
@                                                0         17  25  31
.fib-allmaj-64-3-e &fib.&majorkey.&majoroct.o-1d16h17t+0 t+17 t+8 t+6
.fib-allmaj-64-3-f &fib.&majorkey.&majoroct.o-1d24r0t+0 &fin-ra*.d40h42t+31
@ fast and short
.fib-allmaj-64-4-a &fib.&majorkey.&majoroct.e8o-1d12r0 &fin-ran*.d4t+9 t+8 t+8 d8t+6 d12t+12 d8t+10 d12t+9
@                                                    0     31     43    9           37    48    25      0    9   43
.fib-allmaj-64-4-b &fib.&majorkey.&majoroct.e8o-1d12t+0 d4o-1t+31 t+12 d12t+19 d4o-1t+28 t+11 d12t+30 d4t-25 t+9 t-19
.fib-allmaj-64-4-c &fib.&majorkey.&majoroct.e8d12t+0 d4t+9  d12t-19 d4t+5 d12t-17 d4t+6 d12t-20 d4t-8
@ back beat chords thirds
.fi2-allmaj-32-1-a &fi2.d8r0 &fin-ran*.d0o5h4&majorkey.&maj3-u-a3*.d8 d8r0 &fin-ran*.d0o5h4&majorkey.&maj3-u-a5*.d8
.fi2-allmaj-32-1-b &fi2.d8r0 &fin-ran*.d0o5h4&majorkey.&maj3-u-a*.d8 d8r0 &fin-ran*.d0o5h4&majorkey.&maj3-u-b7*.d4 d0&majorkey.&maj3-u-b7*.d4
.fi2-allmaj-32-1-c &fi2.d8r0 &fin-ran*.d0o5h4&majorkey.&maj3-u-a*.d8 d8r0 &fin-ran*.d0o5h4&majorkey.&maj3-u-b*.d8
.fi2-allmaj-32-1-d &fi2.d8r0 &fin-ran*.d0o5h4&majorkey.&maj3-u-a*.d8 d12r0 &fin-ran*.d0o5h4&majorkey.&maj3-u-b2*.d2 v-4d0o5h4&majorkey.&maj3-u-b2*.d2
.fi2-allmaj-32-1-e &fi2.d4o5h16&majorkey.t+0 v-2t+9 v-2t+8 v-2t+8 v-2t+6 v-2t+6 v-2t+6 v-2d2t+5 t+5
.fi2-allmaj-32-1-f &fi2.d4o6h16&majorkey.t+0 v-2o-1 v-2 v-2 v-2 v-2 v-2 v-2
@ back beat fourths                                    e     a+   d                       d   g     c
@.fi2-allmaj-32-4-a &fi2.d8r0 &fin-ran*.v-2d0o5h4&majorkey.&maj4-u-3.d16 d0o5h4&majorkey.&maj4-u-2.d8
@                                                      e     a+   d                       f+   a+    e
.fi2-allmaj-32-4-b &fi2.d8r0 &fin-ran*.v-2d0o5h4&majorkey.&maj4-u-3.d16 d0o5h4&majorkey.&maj4-u-4.d8
@                                                      d     g   c                      c    f+   b                     d   g     c
@.fi2-allmaj-32-4-c &fi2.d8r0 &fin-ran*.v-2d0o5h4&majorkey.&maj4-u-2.d16 d0o5h4&majorkey.&maj4-u-1.d4 d0o5h4&majorkey.&maj4-u-2.d4
@                                                      c    f+   b                      b   e    a+
@.fi2-allmaj-32-4-d &fi2.d8r0 &fin-ran*.v-2d0o5h4&majorkey.&maj4-u-1.d16 d0o4h4&majorkey.&maj4-u-8.d8
@.fi2-allmaj-32-4-e &fi2.d4o6h16&majorkey.t+0 v-2t-5 v-2t-5 v-2t-6 v-2t-6 v-2t-6 v-2t-8 v-2d2t-8 t-9
@ arpeggio finger piano  thirds
.fi3-allmaj-32-1-a &fi3.v-3o+2&majorkey.d4h32&maj3-d-a3*.d8 &majorkey.d4&maj3-d-b*.d0 v-6&majorkey.o+1&maj3-d-a*.d8
.fi3-allmaj-32-1-b &fi3.v-3o+2&majorkey.d4h32&maj3-d-a1*.d8 &majorkey.d4&maj3-d-b*.d8
.fi3-allmaj-32-1-c &fi3.v-3o+2&majorkey.d4h32&maj3-d-a1*.   &majorkey.d8&maj3-d-b*.d4
.fi3-allmaj-32-1-d &fi3.r0d32
.fi3-allmaj-32-1-e &fi3.v-4o4&majorkey.d4h32&maj3-d-a3*.d8 &majorkey.d4&maj3-d-b*.d8
.fi3-allmaj-32-1-f &fi3.v-4o4&majorkey.d4h32&maj3-d-a1*.   &majorkey.d8&maj3-d-a*.d4
.fi3-allmaj-32-1-g &fi3.r0d32
.fi3-allmaj-32-1-h &fi3.r0d32
@ arpeggio fourths
@                                          e     a+      d      g    c      g    d    a+
.fi3-allmaj-32-4-a &fi3.v-5o+2&majorkey.d4h32t+17 s-1d8t+26 s-1d2t+19 s-1t+22 s-1d4t+22 s-1t-22 s-1t-22 s-1t-19
@                                          d     g    c     f+      b   f+     c    g
@                                          9     31   53    25     48   25     53   31
.fi3-allmaj-32-4-b &fi3.v-5o+2&majorkey.d4h32t+9 s+1t+22 s+1d8t+22 s+1d2t+25 s+1t+23 s+1d4t-23 s+1t-25 s+1t-22
@                                          c     f+   b    e     a+     e    b      f+
@                                          0     25   48   17    43     17   48     25
.fi3-allmaj-32-4-c &fi3.v-5o+2&majorkey.d4h32t+0 s-1t+25 s-1t+23 s-1d8t+22 s-1d2t+26 s-1t-26 s-1d4t-22 s-1t-23
.fi3-allmaj-32-4-d &fi3.r0d32
@                                          a+     d    g     c    f+    c     g     d
@                                         43      9    31    0    25    0     31    9
.fi3-allmaj-32-4-e &fi3.v-5o+2&majorkey.d4h32t-10 s+1t+19 s+1t+22 s+1t+22 s+1d8t+25 s+1d2t-25 s+1t-22 s+1d4t-22
@                                          g      c     f+   b   e    b      f+     c
@                                         31      0    25    48  17   48     25     0
.fi3-allmaj-32-4-f &fi3.v-5o+2&majorkey.d4h32t-22 s-1t+22 s-1t+25 s-1t+23 s-1t+22 s-1d8t-22 s-1d2t-23 s-1t-25
.fi3-allmaj-32-4-g &fi3.r0d32
.fi3-allmaj-32-4-h &fi3.r0d32
@ intro calmer 24 & 40
.fi3-allmaj-64-5-a &fi3.v-5d8h32&majorkey.&majoroct.o+2&maj4-u-3.d8 &fi3.v-5d16h32&majorkey.&majoroct.o+2&maj4-u-2.d8
.fi3-allmaj-64-5-b &fi3.v-5d8h32&majorkey.&majoroct.o+2&maj4-u-3.d8 &fi3.v-5d16h32&majorkey.&majoroct.o+2&maj4-u-4.d8
.fi3-allmaj-64-5-c &fi3.v-5d8h32&majorkey.&majoroct.o+2&maj4-u-2.d8 &fi3.v-5d16h32&majorkey.&majoroct.o+2&maj4-u-1.d8
.fi3-allmaj-64-5-d &fi3.v-5d8h32&majorkey.&majoroct.o+2&maj4-u-1.d8 &fi3.v-5d16h32&majorkey.&majoroct.o+2&maj4-u-8.d8
@ 1239
@ music box arpeggios
.fi3-allmaj-24-6-a &fi3.v-6&majorkey.o5d2h32&maj3-u-a3*. &fi3.v-6&majorkey.o5d2h32&maj3-u-b4*. &fi3.v-6&majorkey.o5d2h32&maj3-u-a5*. &fi3.v-6&majorkey.o5d2h32&maj3-u-b7*.
.fi3-allmaj-24-6-b &fi3.v-6&majorkey.o5d2h32&maj3-u-a1*. &fi3.v-6&majorkey.o5d2h32&maj3-u-b2*. &fi3.v-6&majorkey.o6d2h32&maj3-u-a3*. &fi3.v-6&majorkey.o6d2h32&maj3-u-b4*.
.fi3-allmaj-16-6-a &fi3.v-6&majorkey.o6d2h32&maj3-u-a5*. &fi3.v-6&majorkey.o6d2h32&maj3-u-b7*. &fi3.v-6&majorkey.o6d2h32&maj3-u-a1*.d0
.fi3-allmaj-64-6-a &fi3-allmaj-24-6-a. &fi3-allmaj-24-6-b. &fi3-allmaj-16-6-a.
.fi3-allmaj-24-6-c &fi3.v-6&majorkey.o6d2h32&maj3-u-a3*. &fi3.v-6&majorkey.o6d2h32&maj3-u-b4*. &fi3.v-6&majorkey.o6d2h32&maj3-u-a5*. &fi3.v-6&majorkey.o6d2h32&maj3-u-b7*.
.fi3-allmaj-24-6-d &fi3.v-6&majorkey.o6d2h32&maj3-u-a1*. &fi3.v-6&majorkey.o6d2h32&maj3-u-b2*. &fi3.v-6&majorkey.o7d2h32&maj3-u-a3*. &fi3.v-6&majorkey.o7d2h32&maj3-u-b4*.
.fi3-allmaj-16-6-b &fi3.v-6&majorkey.o7d2h32&maj3-u-a5*. &fi3.v-6&majorkey.o7d2h32&maj3-u-b7*. &fi3.v-6&majorkey.o7d2h32&maj3-u-a1*.d0
.fi3-allmaj-64-6-b &fi3-allmaj-24-6-c. &fi3-allmaj-24-6-d. &fi3-allmaj-16-6-b.
.fi3-allmaj-24-6-e &fi3.v-6&majorkey.o7d2h32&maj3-u-a3*. &fi3.v-6&majorkey.o7d2h32&maj3-u-b4*. &fi3.v-6&majorkey.o7d2h32&maj3-u-a5*. &fi3.v-6&majorkey.o7d2h32&maj3-u-b7*.
.fi3-allmaj-24-6-f &fi3.v-6&majorkey.o7d2h32&maj3-u-a1*. &fi3.v-6&majorkey.o7d2h32&maj3-u-b2*. &fi3.v-6&majorkey.o8d2h32&maj3-u-a3*. &fi3.v-6&majorkey.o8d2h32&maj3-u-b4*.
.fi3-allmaj-16-6-c &fi3.v-6&majorkey.o8d2h32&maj3-u-a5*. &fi3.v-6&majorkey.o8d2h32&maj3-u-b7*. &fi3.v-6&majorkey.o8d2h32&maj3-u-a1*.d0
.fi3-allmaj-64-6-c &fi3-allmaj-24-6-e. &fi3-allmaj-24-6-f. &fi3-allmaj-16-6-c.
@ randomize them
.fi3-allmaj-24-6-g &fi3.v-6&majorkey.o+2d2h32&maj3-u-*. &fi3.v-6&majorkey.o+2d2h32&maj3-u-*. &fi3.v-6&majorkey.o+2d2h32&maj3-u-*. &fi3.v-6&majorkey.o+2d2h32&maj3-u-*.
.fi3-allmaj-24-6-h &fi3.v-6&majorkey.o+2d2h32&maj3-u-*. &fi3.v-6&majorkey.o+2d2h32&maj3-u-*. &fi3.v-6&majorkey.o+3d2h32&maj3-u-*. &fi3.v-6&majorkey.o+3d2h32&maj3-u-*.
.fi3-allmaj-16-6-d &fi3.v-6&majorkey.o+3d2h32&maj3-u-*. &fi3.v-6&majorkey.o+3d2h32&maj3-u-*. &fi3.v-6&majorkey.o+3d2h32&maj3-u-*.d0
.fi3-allmaj-64-6-d &fi3-allmaj-24-6-g. &fi3-allmaj-24-6-h. &fi3-allmaj-16-6-d.
@ music box arpeggios
.fi2-allmaj-24-6-a &fi2.v-6&majorkey.o7u0d2h32&maj3-d-b4*. &fi2.v-6&majorkey.o7u0d2h32&maj3-d-a3*. &fi2.v-6&majorkey.o7u0d2h32&maj3-d-b2*. &fi2.v-6&majorkey.o7u0d2h32&maj3-d-a1*.
.fi2-allmaj-24-6-b &fi2.v-6&majorkey.o7u0d2h32&maj3-d-b7*. &fi2.v-6&majorkey.o7u0d2h32&maj3-d-a5*. &fi2.v-6&majorkey.o6u0d2h32&maj3-d-b4*. &fi2.v-6&majorkey.o6u0d2h32&maj3-d-a3*.
.fi2-allmaj-16-6-a &fi2.v-6&majorkey.o6u0d2h32&maj3-d-b2*. &fi2.v-6&majorkey.o6u0d2h32&maj3-d-a1*. &fi2.v-6&majorkey.o6u0d2h32&maj3-d-b7*.d0
.fi2-allmaj-64-6-a &fi2-allmaj-24-6-a. &fi2-allmaj-24-6-b. &fi2-allmaj-16-6-a.
.fi2-allmaj-24-6-c &fi2.v-6&majorkey.o6u0d2h32&maj3-d-b4*. &fi2.v-6&majorkey.o6u0d2h32&maj3-d-a3*. &fi2.v-6&majorkey.o6u0d2h32&maj3-d-b2*. &fi2.v-6&majorkey.o6u0d2h32&maj3-d-a1*.
.fi2-allmaj-24-6-d &fi2.v-6&majorkey.o6u0d2h32&maj3-d-b7*. &fi2.v-6&majorkey.o6u0d2h32&maj3-d-a5*. &fi2.v-6&majorkey.o5d2h32&maj3-d-b4*. &fi2.v-6&majorkey.o5d2h32&maj3-d-a3*.
.fi2-allmaj-16-6-b &fi2.v-6&majorkey.o5d2h32&maj3-d-b2*. &fi2.v-6&majorkey.o5d2h32&maj3-d-a1*. &fi2.v-6&majorkey.o5d2h32&maj3-d-b7*.d0
.fi2-allmaj-64-6-b &fi2-allmaj-24-6-c. &fi2-allmaj-24-6-d. &fi2-allmaj-16-6-b.
.fi2-allmaj-24-6-e &fi2.v-6&majorkey.o5d2h32&maj3-d-b4*. &fi2.v-6&majorkey.o5d2h32&maj3-d-a3*. &fi2.v-6&majorkey.o5d2h32&maj3-d-b2*. &fi2.v-6&majorkey.o5d2h32&maj3-d-a1*.
.fi2-allmaj-24-6-f &fi2.v-6&majorkey.o5d2h32&maj3-d-b7*. &fi2.v-6&majorkey.o5d2h32&maj3-d-a5*. &fi2.v-6&majorkey.o4d2h32&maj3-d-b4*. &fi2.v-6&majorkey.o4d2h32&maj3-d-a3*.
.fi2-allmaj-16-6-c &fi2.v-6&majorkey.o4d2h32&maj3-d-b2*. &fi2.v-6&majorkey.o4d2h32&maj3-d-a1*. &fi2.v-6&majorkey.o4d2h32&maj3-d-b7*.d0
.fi2-allmaj-64-6-c &fi2-allmaj-24-6-e. &fi2-allmaj-24-6-f. &fi2-allmaj-16-6-c.
@ randomize them
.fi2-allmaj-24-6-g &fi2.v-6&majorkey.o+2d2h32&maj3-d-*. &fi2.v-6&majorkey.o+2d2h32&maj3-d-*. &fi2.v-6&majorkey.o+2d2h32&maj3-d-*. &fi2.v-6&majorkey.o+2d2h32&maj3-d-*.
.fi2-allmaj-24-6-h &fi2.v-6&majorkey.o+2d2h32&maj3-d-*. &fi2.v-6&majorkey.o+2d2h32&maj3-d-*. &fi2.v-6&majorkey.o+1d2h32&maj3-d-*. &fi2.v-6&majorkey.o+1d2h32&maj3-d-*.
.fi2-allmaj-16-6-d &fi2.v-6&majorkey.o+1d2h32&maj3-d-*. &fi2.v-6&majorkey.o+1d2h32&maj3-d-*. &fi2.v-6&majorkey.o+1d2h32&maj3-d-*.d0
.fi2-allmaj-64-6-d &fi2-allmaj-24-6-g. &fi2-allmaj-24-6-h. &fi2-allmaj-16-6-d.
@ 1096
@ bass flute melody
.flu-allmaj-32-1-a &flu.v+5d32r0
.flu-allmaj-64-1-a &flu.v+5d16h18&majorkey.o+1&maj3-u-a3*.d32h34
.flu-allmaj-64-1-b &flu.v+3d64h66&majorkey.o+1
.flu-allmaj-64-1-c &flu.v+3d32h34u1&gls9:8.&majorkey.o+1 g0u0t+9
.flu-allmaj-64-1-d &flu.v+3d64h66t+9o+1
.flu-allmaj-32-1-e &flu.d32r0
.flu-allmaj-64-1-e &flu.d16r0 &flu-ran*.d8h10&majorkey.o+1&maj3-u-b2*.d32h34
.flu-allmaj-64-1-f &flu.d32h34&gls8:7.t+43o+1 g0o+1&majorkey.
.flu-allmaj-64-1-g &flu.d64h32&majorkey.o+2
.flu-allmaj-64-1-h &flu.d16r0 &flu-ran*.d48h50o+2t+17
.flu-allmaj-64-1-i &flu.d64h66o+2t+17
.flu-allmaj-16-1-j &flu.d16r0
@ flute slow to half speed
.flu-allmaj-64-2-a &flu.v+3d32h34&majorkey.o+1&maj3-u-a3*.d0h0
.flu-allmaj-64-2-b &flu.v+3d64h48&majorkey.o+1
.flu-allmaj-64-2-d &flu.v+3d32h34u1&gls9:8.&majorkey.o+1 u0g0t+9
.flu-allmaj-64-2-e &flu.d64r0
@ 1212
@ flute chords & slides
.flu-allmaj-64-3-a &flu.d8h10e8&majorkey.v+6t+17 d4h0t+14 t+22 d8h9&majorkey.t+9 v-2d4h0t+16 t+18 d8h9&majorkey.t+17 v-2d4h0t+14 t+22 o-1d8h9&majorkey.t+9 v-2d4h0t+16 e1t+18h24
.flu-allmaj-64-3-b &flu.d64r0
.flu-allmaj-64-3-c &flu.v+4d16r0 &flu-r*.e8d0h24&majorkey.o+2&maj3-u-a1*.d32r0 &flu-r*.d0h24&majorkey.&maj3-u-b*.d16r0
.flu-allmaj-64-3-d &flu.&ce2-ran*.e8o+2d0h8&majork*.t+9 t+16d8 d0h8&majork*.t+0 t+17d8 d0h18&majork*.o-1t+43 t+19d16 d0h8&majork*.o-1t+31 t+22d8 d0h18&majork*.o-1t+25 t+18d16 d0h8&majork*.t+17 t+14d8
.flu-allmaj-64-3-e &flu.e8d0h10&majorkey.o+1t+17 t+14d8 d0h16&majorkey.t+17 t+14d24 d16h20e1&majorkey.t+17&gls6:5. e8t+14t+22g0
.flu-allmaj-64-3-f &flu.d64r0
.flu-allmaj-64-3-g &flu.d16r0 &flu-r*.d16h20e1&majorkey.o+1t+17&gls6:5. e1e8t+36g0 o-1&gls5:4. e8t+31g0d0
.flu-allmaj-64-3-h &flu.d64r0
.flu-allmaj-64-3-i &flu.&ce2-ran*.e8o+1d0h18&majork*.t+25 t+18d16 d0h8&majork*.t+17 t+14d8 d0h8&majork*.t+9 t+16d8 d0h8&majork*.t+0 t+17d8 d0h18&majork*.o-1t+43 t+19d16 d0h8&majork*.o-1t+31 t+22d8
.flu-allmaj-64-3-j &flu.d64r0
@
@       c  to d      e      f+      g      a+
@ trill t0 to t9 and t17 to t25 and t31 to t43
@        t+9         t+8            t+12
@ flute trill triads
.flu-allmaj-64-4-a &flu.d0h64v-8&majorkey.&dsx-ran*.o+1&trl9:8.    t+17&trl11:10. t+14&trl7:6.d64
.flu-allmaj-64-4-b &flu.d0h64v-8&majorkey.&dsx-ran*.t+17&trl11:10. t+14&trl7:6.   t+22&trl9:8.d64
.flu-allmaj-64-4-c &flu.d0h64v-8&majorkey.&dsx-ran*.t+31&trl7:6.   t+22&trl9:8.   t+17&trl11:10.d64
.flu-allmaj-64-4-d &flu.&majorkey.&majoroct.o+1e8d12r0 &flu-ran*.d4t+9 t+8 t+8 d8t+6 d12t+12 d8t+10 d12t+9
.flu-allmaj-64-4-e &flu.r0d64
@ faster flute trill triads
.flu-allmaj-64-6-a &flu.d0h24v-1e16&majorkey.o+1  t+17 t+14d24 &flu.d0h40v-1e16&majorkey.&dsx-ran*.o+1&trl9:8.    t+17&trl11:10. t+14&trl7:6.d40
.flu-allmaj-64-6-b &flu.d0h24v-1e16&majorkey.t+17 t+14 t+22d24 &flu.d0h40v-1e16&majorkey.&dsx-ran*.t+17&trl11:10. t+14&trl7:6.   t+22&trl9:8.d40
.flu-allmaj-64-6-c &flu.d0h24v-1e16&majorkey.t+31 t+22 t+17d24 &flu.d0h40v-1e16&majorkey.&dsx-ran*.t+31&trl7:6.   t+22&trl9:8.   t+17&trl11:10.d40
.flu-allmaj-64-6-d &flu.d0h64v-1e16&majorkey.&dsx-ran*.o+1&trl9:8.    t+17&trl11:10. t+14&trl7:6.d64
.flu-allmaj-64-6-e &flu.d0h64v-1e16&majorkey.&dsx-ran*.t+17&trl11:10. t+14&trl7:6.   t+22&trl9:8.d64
.flu-allmaj-64-6-f &flu.d0h64v-1e16&majorkey.&dsx-ran*.t+31&trl7:6.   t+22&trl9:8.   t+17&trl11:10.d64
@ cello backing the flute melody
@ 1236
.cel-allmaj-32-1-a &cel.d32r0
.cel-allmaj-32-1-e &cel.d32r0
.cel-allmaj-64-1-a &cel.d64r0
.cel-allmaj-64-1-b &cel.v-8d24h18&majorkey. t+31d40
.cel-allmaj-64-1-c &cel.v-8d24h18&majorkey. t+31d40
.cel-allmaj-64-1-d &cel.e16d64h66t+9
.cel-allmaj-64-1-e &cel.d16r0 &cel-r*.v-5d8h10&majorkey.o+1&maj3-u-b2*.d32h34e16
.cel-allmaj-64-1-f &cel.d16r0 &cel-r*.v-5e8d0h24&majorkey.o+1&maj3-u-a*.d32r0 &cel-r*.d0h24&majorkey.o+1&maj3-u-b*.d16r0
.cel-allmaj-64-1-g &cel.d16r0 &cel-r*.v-8d48h32&majorkey.o+2
.cel-allmaj-64-1-h &cel.d16r0 &cel-r*.v-8d48h50&majorkey.o+1t+17
.cel-allmaj-64-1-i &cel.&majorkey.e16d64h66t+43
.cel-allmaj-16-1-j &cel.d16r0
@ cello slow down
.cel-allmaj-64-2-a &cel.v-2d16h18&majorkey.o+1 t+31 t-31d32h34
.cel-allmaj-64-2-b &cel.v-2d64h48&majorkey.o+1
.cel-allmaj-64-2-d &cel.v-2d16h18&majorkey.o+1 t+31 t-31d32h34
.cel-allmaj-64-2-e &cel.d64r0
@ cello slides and chords duplicates flute
@ 1254
.cel-allmaj-64-3-a &cel.d8h10e8v-3&majorkey.t+17 d4h0t+14 t+22 d8h9&majorkey.t+9 v-2d4h0t+16 t+18 d8h9&majorkey.t+17 v-2d4h0t+14 t+22 d8h9&majorkey.t+9 v-2d4h0t+16 e1t+18h24
.cel-allmaj-64-3-b &cel.d64r0
.cel-allmaj-64-3-c &cel.d16r0 &cel-r*.v-3e8d0h24&majorkey.o+2&maj3-u-a1*.d32r0 &cel-r*.d0h24&majorkey.&maj3-u-b*.d16r0
.cel-allmaj-64-3-d &cel.&ce2-ran*.v-3e8o+2d0h8&majork*.t+9 t+16d8 d0h8&majork*.t+0 t+17d8 d0h18&majork*.o-1t+43 t+19d16 d0h8&majork*.o-1t+31 t+22d8 d0h18&majork*.o-1t+25 t+18d16 d0h8&majork*.t+17 t+14d8
.cel-allmaj-64-3-e &cel.e8d0h10v-3&majorkey.o+2t+17 t+14d8 d0h16&majorkey.t+17 t+14d24 d16h20e1&majorkey.t+17&gls6:5. e8t+14t+22g0
.cel-allmaj-64-3-f &cel.d64r0
.cel-allmaj-64-3-g &cel.d16r0 &cel-r*.v-3d16h20e1&majorkey.o+1t+17&gls6:5. e1e8t+36g0 o-1&gls5:4. e8t+31g0d0
.cel-allmaj-64-3-h &cel.d64r0
.cel-allmaj-64-3-i &cel.&ce2-ran*.v-3e8o+3d0h18&majork*.o-1t+25 t+18d16 d0h8&majork*.t+17 t+14d8 d0h8&majork*.t+9 t+16d8 d0h8&majork*.t+0 t+17d8 d0h18&majork*.o-1t+43 t+19d16 d0h8&majork*.o-1t+31 t+22d8
.cel-allmaj-64-3-j &cel.d64r0
@ trill triads
.cel-allmaj-64-4-a &cel.d0h64v-8&majorkey.&dsx-ran*.o+1&trl9:8.    t+17&trl11:10. t+14&trl7:6.d64
.cel-allmaj-64-4-b &cel.d0h64v-8&majorkey.&dsx-ran*.t+17&trl11:10. t+14&trl7:6.   t+22&trl9:8.d64
.cel-allmaj-64-4-c &cel.d0h64v-8&majorkey.&dsx-ran*.t+31&trl7:6.   t+22&trl9:8.   t+17&trl11:10.d64
.cel-allmaj-64-4-d &cel.&majorkey.&majoroct.v-5o+1e8d12r0 &cel-ran*.d4t+9 t+8 t+8 d8t+6 d12t+12 d8t+10 d12t+9
.cel-allmaj-64-4-e &cel.r0d64
@ cello gets more frantic - counters the flute trills
.cel-allmaj-64-5-a &cel.&majorkey.&majoroct.o+1e8d12r0 &cel-ran*.d4t+9 t+8 t+8 d8t+6 d12t+12 d8t+10 d12t+9
.cel-allmaj-64-5-b &cel.&majorkey.&majoroct.o+1e8d12t+0 d4o-1t+31 t+12 d12t+19 d4o-1t+28 t+11 d12t+31 d4t-26 t+10 t+31
.cel-allmaj-64-5-c &cel.&majorkey.&majoroct.o+1e8d12t+0 d4t+9  d12t-19 d4t+5 d12t-17 d4t+6 d12t-20 d4t-8
.cel-allmaj-64-5-d &cel.d0h64v-8&majorkey.&dsx-ran*.o+1&trl9:8.    t+17&trl11:10. t+14&trl7:6.d64
.cel-allmaj-64-5-e &cel.d64r0
@ faster trill triads
.cel-allmaj-64-6-a &cel.d0h24v-4e16&majorkey.o+1  t+17 t+14d24 &cel.d0h40v-4e16&majorkey.&dsx-ran*.o+1&trl9:8.    t+17&trl11:10. t+14&trl7:6.d40
.cel-allmaj-64-6-b &cel.d0h24v-4e16&majorkey.t+17 t+14 t+22d24 &cel.d0h40v-4e16&majorkey.&dsx-ran*.t+17&trl11:10. t+14&trl7:6.   t+22&trl9:8.d40
.cel-allmaj-64-6-c &cel.d0h24v-4e16&majorkey.t+31 t+22 t+17d24 &cel.d0h40v-4e16&majorkey.&dsx-ran*.t+31&trl7:6.   t+22&trl9:8.   t+17&trl11:10.d40
.cel-allmaj-64-6-d &cel.d0h64v-4e16&majorkey.&dsx-ran*.o+1&trl9:8.    t+17&trl11:10. t+14&trl7:6.d64
.cel-allmaj-64-6-e &cel.d0h64v-4e16&majorkey.&dsx-ran*.t+17&trl11:10. t+14&trl7:6.   t+22&trl9:8.d64
.cel-allmaj-64-6-f &cel.d0h64v-4e16&majorkey.&dsx-ran*.t+31&trl7:6.   t+22&trl9:8.   t+17&trl11:10.d64
@ 1272
@ all minor keys
@  utonality minor
@  1  2  3  4  5  6  7  8  1  2  3  4  5  6  7   8   1
@  0  7 14 22 31 36 41 47 53 60 67 75 84 89 94 100 105
@    +7 +7 +8 +9 +5 +5 +6 +6 +7 +7 +8 +9 +5 +5  +6  +6
@      +14   +17         +22
@  0      +22      +19
@     7      +24       +16
@       14      +22      +17
@
@    +7   +15      +19       +19
@ ratio num 1 12 6 4 3 8 12 24 1
@ ratio den 1 11 5 3 2 5 7 13 1
@ name      C D  E  F  G  A  A  B  C  D  E  F  G  A  A   B   C
@ #         1 2  3  4  5  6  7  8  1  2  3  4  5  6  7   8   9
@ absolute  0 7 14 22 31 36 41 47 53 60 67 75 84 89 94 100 106
@ steps      +7 +7 +8 +9 +5 +5 +6 +6 +7 +7 +8 +9 +5 +5  +6  +6
@ thirds a    +14   +17   +22
@ thirds b   7   +15   +19   +19
@ fourths   0  +22  +19  +19
@ fourths   7  +24  +22  +22
@ fourths  14  +22  +24  +22
@ fourths  22  +19  +19  +24
@ fourths  31  +22  +22  +19
@ fourths  36  +24  +24  +22
@ fourths  41  +19  +24  +22
@ fourths  47  +20  +22  +24
@ start in the key of e t17
@ c  d  d  e  f  g  a  b
@ 0  5 11 17 24 31 39 48
@ bass line simple to start
.fib-allmin-64-1-a &fib.&minorkey.&minoroct.d16o-1 t+31 t-31d32
.fib-allmin-64-1-b &fib.&minorkey.&minoroct.d24o-1 d16t+31 d24t+22
.fib-allmin-64-1-c &fib.&minorkey.&minoroct.d16o-1 t+31 t-31d24 d8e8o-1t+41
@ bass line scales
@                                                                 7    14   22  31        41    47    0
.fib-allmin-64-2-a &fib.&minorkey.&minoroct.e8o-1d12r0 &fin-ran*.d4t+7 t+7 t+8 d8t+9 d12t+10 d8t+6 d12t+6
@                                                   0       31     0      14   31          0      14   0     22     41
.fib-allmin-64-2-b &fib.&minorkey.&minoroct.e8o-1d12t+0 d4o-1t+31 t+22 d12t+14 d4o-1t+17 t+22 d12t+14 d4t-14 t+22 t+19
@                                               0     7      41     47      36    41       22    14
.fib-allmin-64-2-c &fib.&minorkey.&minoroct.e8d12t+0 d4t+7  d12t-19 d4t+6 d12t-11 d4t+5 d12t-19 d4t-8
@ bass slow down
.fib-allmin-64-3-a &fib.&minorkey.&minoroct.o-1d64t+0
.fib-allmin-64-3-b &fib.&minorkey.&minoroct.o-1d24h64t+0 d40h48o+1
.fib-allmin-64-3-c &fib.&minorkey.&minoroct.d24t+0h64 d40h48t+31
.fib-allmin-64-3-d &fib.&minorkey.&minoroct.o-1d24h64t+0 d40h48t+31
.fib-allmin-64-3-e &fib.&minorkey.&minoroct.o-1d16h17t+0 t+14 t+8 t+9
.fib-allmin-64-3-f &fib.&minorkey.&minoroct.o-1d24r0t+0 &fin-ra*.d40h42t+31
@ third chords back beat
.fi2-allmin-32-1-a &fi2.d8r0 &fin-ran*.d0h4&minorkey.&minoroct.o+2&min3-u-a3*.d16 &fi2.d0h4&minorkey.&minoroct.o+2&min3-u-a5*.d8
.fi2-allmin-32-1-b &fi2.d8r0 &fin-ran*.d0h4&minorkey.&minoroct.o+2&min3-u-a*.d16  &fi2.d0h4&minorkey.&minoroct.o+2&min3-u-b7*.d4 &fi2.d0h4&minorkey.&minoroct.o+2&min3-u-b7*.d4
.fi2-allmin-32-1-c &fi2.d8r0 &fin-ran*.d0h4&minorkey.&minoroct.o+2&min3-u-a*.d16  &fi2.d0h4&minorkey.&minoroct.o+2&min3-u-b*.d8
.fi2-allmin-32-1-d &fi2.d8r0 &fin-ran*.d0h4&minorkey.&minoroct.o+2&min3-u-a*.d20  &fi2.d0h4&minorkey.&minoroct.o+2&min3-u-b2*.d2 &fi2.v-4d0h4&minorkey.&minoroct.o+2&min3-u-b2*.d2
.fi2-allmin-32-1-e &fi2.d4o6h16&minorkey.t+0 v-2t-6 v-2t-6 v-2t-5 v-2t-5 v-2t-9 v-2t-8 v-2d2t-7 t-7
@ fourth chords back beat
.fi2-allmin-32-2-a &fi2.d8r0 &fin-ran*.v-2d0h4&minorkey.&minoroct.o+1&min4-u-6.d16 &fi2.d0h4&minorkey.&minoroct.o+1&min4-u-5.d8
.fi2-allmin-32-2-b &fi2.d8r0 &fin-ran*.v-2d0h4&minorkey.&minoroct.o+1&min4-u-8.d16 &fi2.d0h4&minorkey.&minoroct.o+1&min4-u-7.d8
.fi2-allmin-32-2-c &fi2.d8r0 &fin-ran*.v-2d0h4&minorkey.&minoroct.o+1&min4-u-5.d16 &fi2.d0h4&minorkey.&minoroct.o+1&min4-u-6.d4 &fi2.d0h4&minorkey.&minoroct.o+1&min4-u-5.d4
.fi2-allmin-32-2-d &fi2.d8r0 &fin-ran*.v-2d0h4&minorkey.&minoroct.o+1&min4-u-7.d16 &fi2.d0h4&minorkey.&minoroct.o+1&min4-u-5.d8
.fi2-allmin-32-2-e &fi2.d4o6h16&minorkey.t+0 v-2t-6 v-2t-6 v-2t-5 v-2t-5 v-2t-9 v-2t-8 v-2d2t-7 t-7
@ 1333
@ slow down
.fi2-allmin-64-3-a &fi2.v-2d0h64&minorkey.&minoroct.o+2&min4-u-4.d24 &fi2.d0h48&minorkey.&minoroct.o+2&min4-u-3.d40
.fi2-allmin-64-3-b &fi2.v-2d0h64&minorkey.&minoroct.o+3&min4-u-2.d24 &fi2.d0h48&minorkey.&minoroct.o+3&min4-u-1.d40
.fi2-allmin-64-3-c &fi2.v-2d0h64&minorkey.&minoroct.o+1&min4-u-8.d24 &fi2.d0h48&minorkey.&minoroct.o+2&min4-u-1.d40
.fi2-allmin-64-3-d &fi2.v-2d0h64&minorkey.&minoroct.o+2&min4-u-6.d24 &fi2.d0h48&minorkey.&minoroct.o+2&min4-u-7.d40
.fi2-allmin-64-3-e &fi2.r0d64
@ flute minor melody
.flu-allmin-64-1-a &flu.d16h18v+3&minorkey.&minoroct.o+2t-12 &minorkey.o-1d4h5&min3-d-a5*.d8h9 &minorkey.o-2d4h5&min3-d-b7*.d8h9 &minorkey.o-1d4h5&min3-d-a5*.d8h10
.flu-allmin-64-1-b &flu.d64h34v+3&minorkey.&minoroct.o+1
.flu-allmin-64-1-c &flu.d16h18v+3&minorkey.&minoroct.o+1t-17 t+5 t+6 t+6
.flu-allmin-64-1-d &flu.d16r0 v+3&flu-ran*.d48h50&minorkey.&minoroct.o+1t+14
.flu-allmin-64-1-e &flu.d64h34v+3&minorkey.&minoroct.t+22
.flu-allmin-64-1-f &flu.d8h10v+3&minorkey.&minoroct.o+1t-12 &minorkey.d4h5&min3-u-a5*.d8h9 &minorkey.d4h5&min3-u-b7*.d8h9 &minorkey.d4h5&min3-u-a1*.d16h18o-1
.flu-allmin-64-1-g &flu.d64h34v+3&minorkey.&minoroct.t+31
@ flute melody in fourths
.flu-allmin-64-2-a &flu.d16h18&minorkey.&minoroct.o+2t-12 &minorkey.o-1d4h5&min4-d-*.d8h9 &minorkey.d4h5&min4-d-*.d8h9 &minorkey.d4h5&min4-d-*.d8h10
.flu-allmin-64-2-b &flu.d64h34&minorkey.&minoroct.o+1
.flu-allmin-64-2-c &flu.d16h18&minorkey.&minoroct.o+1t-17 t+5 t+6 t+6
.flu-allmin-64-2-d &flu.d16r0 &flu-ran*.d48h50&minorkey.&minoroct.o+1t+14
.flu-allmin-64-2-e &flu.d64h34&minorkey.&minoroct.t+22
.flu-allmin-64-2-f &flu.d8h10&minorkey.&minoroct.o+1t-12 &minorkey.d4h5&min4-u-*.d8h9 &minorkey.d4h5&min4-u-*.d8h9 &minorkey.d4h5&min4-u-*.d16h18o-1
.flu-allmin-64-2-g &flu.d64h34&minorkey.&minoroct.t+31
@ flute slow down
@ flute trills
.flu-allmin-64-3-a &flu.d0h64&minorkey.&minoroct.&dsx-ran*.e15t+0o+1&trl12:11. t+14&trl10:9. t+17&trl16:15.d64
.flu-allmin-64-3-b &flu.d0h64&minorkey.&minoroct.&dsx-ran*.e15t+0o+1 t+14 t+17d64
.flu-allmin-64-3-c &flu.d64r0
@ flute trills
.flu-allmin-64-4-a &flu.d0h64&minorkey.&minoroct.&dsx-ran*.t+0o+1&trl12:11. t+22&trl9:8. t+19&trl14:13.d64
.flu-allmin-64-4-b &flu.d0h64&minorkey.&minoroct.&dsx-ran*.t+14o+1&trl10:9. t+22&trl15:14. t+24&trl11:10.d64
.flu-allmin-64-4-c &flu.d0h64&minorkey.&minoroct.&dsx-ran*.t+31&trl16:15. t+22&trl12:11. t+22&trl9:8.d64
.flu-allmin-64-4-d &flu.d0h64&minorkey.&minoroct.&dsx-ran*.t+41&trl14:13. t+19&trl11:10. t+24&trl16:15.d64
@ is it trills or not? Why do the next four lines override the previous four? What was I thinking here?
.flu-allmin-64-4-a &flu.d0h64&minorkey.&minoroct.&dsx-ran*.t+0o+1  t+22 t+19d64
.flu-allmin-64-4-b &flu.d0h64&minorkey.&minoroct.&dsx-ran*.t+14o+1 t+22 t+24d64
.flu-allmin-64-4-c &flu.d0h64&minorkey.&minoroct.&dsx-ran*.t+31    t+22 t+22d64
.flu-allmin-64-4-d &flu.d0h64&minorkey.&minoroct.&dsx-ran*.t+41    t+19 t+24d64
@ repeat just to show the drift
.flu-allmin-64-5-a &flu.d0h64v-3&minorkey.&minoroct.o+1e15&min3-u-a5*.d64
.flu-allmin-64-5-b &flu.d0h64v-3&minorkey.&minoroct.o+1e15&min3-u-a3*.d64
.flu-allmin-64-5-c &flu.d0h64v-3&minorkey.&minoroct.o+1e15&min3-u-a1*.d64
@ cello melody minor
@
.cel-allmin-64-0-a &cel.d16h18v-3&minorkey.&minoroct.o+2t-12 &minorkey.o-1d4h5&min3-d-a5*.d8h9 &minorkey.o-2d4h5&min3-d-b7*.d8h9 &minorkey.o-1d4h5&min3-d-a5*.d8h10
@
.cel-allmin-64-1-b &cel.d64h34v-2&minorkey.&minoroct.o+1
.cel-allmin-64-1-c &cel.d16h18v-4&minorkey.&minoroct.o+1t-17 t+5 t+6 t+6
.cel-allmin-64-1-d &cel.d16r0 &cel-ran*.v-3d48h50&minorkey.&minoroct.o+1t+14
.cel-allmin-64-1-e &cel.d64h34v-3&minorkey.&minoroct.t+22
.cel-allmin-64-1-f &cel.d24h26o+1v-3&minorkey.&minoroct. t+31d40h42
.cel-allmin-64-1-g &cel.d16r0 &cel-r*.v-3e8d2h24&minorkey.&minoroct.o+2&min3-u-a*.d28r0 &cel-r*.d2h24&minorkey.&min3-u-b*.d12r0
@ cello melody in fourths
.cel-allmin-64-2-b &cel.d64h34&minorkey.&minoroct.o+1
.cel-allmin-64-2-c &cel.d16h18v-4&minorkey.&minoroct.o+1t-17 t+5 t+6 t+6
.cel-allmin-64-2-d &cel.d16r0 &cel-ran*.d48h50&minorkey.&minoroct.o+1t+14
.cel-allmin-64-2-e &cel.d64h34&minorkey.&minoroct.t+22
.cel-allmin-64-2-f &cel.d16h24&minorkey.&minoroct. t+31d48
.cel-allmin-64-2-g &cel.d16r0 &cel-r*.e8d0h24&minorkey.&minoroct.o+2&min4-u-*.d32r0 &cel-r*.d0h24&minorkey.&min4-u-*.d16r0
@ 1385
@ cello trills slow down
.cel-allmin-64-3-a &cel.d0h64v+7&minorkey.&minoroct.&dsx-ran*.e15t+0o+1&trl12:11. t+14&trl10:9. t+17&trl16:15.d64
.cel-allmin-64-3-b &cel.d0h64v+7&minorkey.&minoroct.&dsx-ran*.e15t+0o+1 t+14 t+17d64
.cel-allmin-64-3-c &cel.d64r0
@ cello trills
.cel-allmin-64-4-a &cel.d0h64&minorkey.&minoroct.&dsx-ran*.t+0o+1&trl12:11. t+22&trl9:8. t+19&trl14:13.d64
.cel-allmin-64-4-b &cel.d0h64&minorkey.&minoroct.&dsx-ran*.t+14o+1&trl10:9. t+22&trl15:14. t+24&trl11:10.d64
.cel-allmin-64-4-c &cel.d0h64&minorkey.&minoroct.&dsx-ran*.t+31&trl16:15. t+22&trl12:11. t+22&trl9:8.d64
.cel-allmin-64-4-d &cel.d0h64&minorkey.&minoroct.&dsx-ran*.t+41&trl14:13. t+19&trl11:10. t+24&trl16:15.d64
.cel-allmin-64-4-e &cel.d0h64&minorkey.&minoroct.&dsx-ran*.t+0o+1  t+22 t+19d64
.cel-allmin-64-4-f &cel.d0h64&minorkey.&minoroct.&dsx-ran*.t+14o+1 t+22 t+24d64
.cel-allmin-64-4-g &cel.d0h64&minorkey.&minoroct.&dsx-ran*.t+31    t+22 t+22d64
.cel-allmin-64-4-h &cel.d0h64&minorkey.&minoroct.&dsx-ran*.t+41    t+19 t+24d64
@ repeat just to show the drift
.cel-allmin-64-5-a &cel.d0h64o+2v+2&minorkey.&minoroct.e15&min3-u-a5*.d64
.cel-allmin-64-5-b &cel.d0h64o+2v+2&minorkey.&minoroct.e15&min3-u-a3*.d64
.cel-allmin-64-5-c &cel.d0h64o+1v+2&minorkey.&minoroct.e15&min3-u-a1*.d64
@ minor thirds arpeggios
.fi3-allmin-32-1-a &fi3.v-3o+2&minorkey.&minoroct.d4h32&min3-d-a3*.d8 &fi3.o+2&minorkey.&minoroct.h32d4&min3-d-b*.d0 &fi3.v-6o+1d0&minorkey.&minoroct.h32&min3-d-a*.d8
.fi3-allmin-32-1-b &fi3.v-3o+2&minorkey.&minoroct.d4h32&min3-d-a1*.d8 &fi3.o+2&minorkey.&minoroct.h32d4&min3-d-b*.d8
.fi3-allmin-32-1-c &fi3.v-3o+2&minorkey.&minoroct.d4h32&min3-d-a1*.   &fi3.o+2&minorkey.&minoroct.h32d8&min3-d-b*.d4
.fi3-allmin-32-1-d &fi3.r0d32
.fi3-allmin-32-1-e &fi3.v-4o+2&minorkey.&minoroct.d4h32&min3-d-a3*.d8 &fi3.o+2&minorkey.&minoroct.h32d4&min3-d-b*.d8
.fi3-allmin-32-1-f &fi3.v-4o+1&minorkey.&minoroct.d4h32&min3-d-a1*.   &fi3.o+1&minorkey.&minoroct.h32d8&min3-d-a*.d4
.fi3-allmin-32-1-g &fi3.r0d32
.fi3-allmin-32-1-h &fi3.r0d32
@ minor fourths arpeggios
.fi3-allmin-32-2-a &fi3.v-3o+2&minorkey.&minoroct.d4h32&min4-d-*.d8 &fi3.o+2&minorkey.&minoroct.h32d4&min4-d-*.d0 &fi3.o+2v-6&minorkey.&minoroct.o+1h32&min4-d-*.d8
.fi3-allmin-32-2-b &fi3.v-3o+2&minorkey.&minoroct.d4h32&min4-d-*.d8 &fi3.o+2&minorkey.&minoroct.h32d4&min4-d-*.d8
.fi3-allmin-32-2-c &fi3.v-3o+2&minorkey.&minoroct.d4h32&min4-d-*.   &fi3.o+2&minorkey.&minoroct.h32d8&min4-d-*.d4
.fi3-allmin-32-2-d &fi3.r0d32
.fi3-allmin-32-2-e &fi3.v-4o+2&minorkey.&minoroct.d4h32&min4-d-*.d8 &fi3.o+2&minorkey.&minoroct.h32d4&min4-d-*.d8
.fi3-allmin-32-2-f &fi3.v-4o+2&minorkey.&minoroct.d4h32&min4-d-*.   &fi3.o+2&minorkey.&minoroct.h32d8&min4-d-*.d4
.fi3-allmin-32-2-g &fi3.r0d32
.fi3-allmin-32-2-h &fi3.r0d32
@ 1417
@ arpeggio slow down
@
@                                                     14      36        60/7    31        53/0      31       7         36
@                                                      E       A         D      G         C         G        D          A
.fi3-allmin-32-3-a &fi3.v-5o+2&minorkey.&minoroct.d4h32t+14 s-1d8t+22 s-1d2t+24 s-1t+24   s-1d4t+22 s-1t-22   s-1t-24   s-1t-24
@                       ;                              7       31       53/0     22        41
@                                                      D        G       C        F         A           F       C         G
.fi3-allmin-32-3-b &fi3.v-5o+2&minorkey.&minoroct.d4h32t+7  s+1t+24   s+1d8t+22 s+1d2t+22 s+1t+19   s+1d4t-19 s+1t-22   s+1t-22
@                                                    0      22         41     60/7       31
@                                                    C      F          A       D          G
.fi3-allmin-32-3-c &fi3.v-5o+2&minorkey.&minoroct.d4h32t+0  s-1t+22   s-1t+19   s-1d8t+19 s-1d2t+24 s-1t-24   s-1d4t-19 s-1t-22
@                                                    41     60/7       31       53/0      22
@                                                    B       D          G        C         F
.fi3-allmin-32-3-d &fi3.v-5o+2&minorkey.&minoroct.d4h32t-12 s+1t+19   s+1t+24   s+1t+22   s+1d8t+22 s+1d2t-22 s+1t-22   s+1d4t-24
@                                                    31    53/0       22        41       60/7
@                                                    G      C         F          A       D
.fi3-allmin-32-3-e &fi3.v-5o+2&minorkey.&minoroct.d4h32t-22 s-1t+22   s-1t+22   s-1t+19   s-1t+19   s-1d8t-19 s-1d2t-19 s-1t-22
.fi3-allmin-32-3-f &fi3.r0d32
@                                                      C0       G31      D9      A 36      E14       B47      E14      A36
.fi3-allmin-32-3-g &fi3.v-5o+3&minorkey.&minoroct.d4h32t+0 s-1d8t-22 s-1d2t-26 s-1t-22  s-1d4t-20 s-1t-25   s-1t+25 s-1t+20
@                                                     A36     E14     B47      F22      C0        G31       C0         F
.fi3-allmin-32-3-h &fi3.v-5o+3&minorkey.&minoroct.d4h32t-22 s-1t-20 s-1d8t-25 s-1d2t-22  s-1t-22  s-1d4t-22 s-1t+22 s-1t+22
@ arpeggio steps
@                                                       E     D       C       B        A      A     G         F
.fi3-allmin-32-3-i &fi3.v-5o+3&minorkey.&minoroct.d4h32t+14 s-1t-7 s-1t-7 s-1d8t-6 s-1d2t-6 s-1t-5 s-1d4t-5 s-1t-9
@                                                     D       C       B        A      A     G         F     E
.fi3-allmin-32-3-j &fi3.v-5o+3&minorkey.&minoroct.d4h32t+7 s-1t-7 s-1d8t-6 s-1d2t-6 s-1t-5 s-1d4t-5 s-1t-9  s-1t-8
@                                                    C       B        A      A     G         F     E
.fi3-allmin-32-3-k &fi3.v-5o+3&minorkey.&minoroct.d4h32 s-1d8t-6 s-1d2t-6 s-1t-5 s-1d4t-5 s-1t-9  s-1t-8 s-1t-7
.fi3-allmin-32-3-l &fi3.r0d32
@ 1449
@ intro calmer 24 & 40
.fi3-allmin-64-4-a &fi3.v-5o+1d8h32&minorkey.&minoroct.o+1&min4-u-6.d8 &fi3.v-5o+1d16h32&minorkey.&minoroct.o+1&min4-u-5.d8
.fi3-allmin-64-4-b &fi3.v-5o+1d8h32&minorkey.&minoroct.o+1&min4-u-8.d8 &fi3.v-5o+1d16h32&minorkey.&minoroct.o+1&min4-u-7.d8
.fi3-allmin-64-4-c &fi3.v-5o+1d8h32&minorkey.&minoroct.o+1&min4-u-5.d8 &fi3.v-5o+1d16h32&minorkey.&minoroct.o+1&min4-u-6.d8
.fi3-allmin-64-4-d &fi3.v-5o+1d8h32&minorkey.&minoroct.o+1&min4-u-7.d8 &fi3.v-5o+1d16h32&minorkey.&minoroct.o+1&min4-u-5.d8
@ 1454
@  combine them
@ circle of fourths
@   18 40 09 31 00 22 44 13 35 04 26 48
@   @
@   17 39 08 30 52 21 43 12 34 03 25 47
@   16 38 07 29 51 20 42 11 33 02 24 46
@   15 37 06 28 50 19 41 10 32 01 23 45
@   14 36 05 27 49 18 40 09 31 00 22 44
@   13 35 04 26 48
@ silent one or more voices if needed
@ random pattern p33 = sequential forward p34 = seq back p2 = try to not repeat p28 = try to repeat
@ all major keys
@ ratio num 1  9  5 11  3 13  7 15  1
@ ratio den 1  8  4  8  2  8  4  8  1
@ name      C  D  E  F  G  A  B  B  C
@           1  2  3  4  5  6  7  8  1  2  3  4  5  6  7   8   1
@ absolute  0  9 17 25 31 37 43 48 53 62 70 78 84 90 96 101 106
@ steps      9  8  8  6  6  6  5  5  9  8  8  6  6  6  5   5
@ thirds a       17    14          22
@ thirds b          16       18       19
.flu-allmaj-40-7-a &flu-pva*.&flu.v+11d4e8h5o+1&majork*.&maj3-u*.r0d0 &flu.v+11d4e8h5&majork*.&maj3-d*.d8h9 &flu.v+11d4e8h5o+1&majork*.&maj3-u*.r0d0 &flu.v+11d4e8h5&majork*.&maj3-d*.d0r0
.flu-allmaj-24-7-a &flu.v+11d4e8h5o+1&majork*.&maj3-u*.r0d0 &flu.v+11d4e8h5&majork*.&maj3-d*.h9d8
.flu-allmaj-64-7-a &flu-allmaj-40-7-a. &flu-allmaj-24-7-a.
.flu-allmaj-64-7-b &flu-pva*.&flu.o+1d0h24v+1&majorkey.&maj3-u*.d24r0 &flu-pva*.&flu.o+1v+1d0&majorkey.h24&maj3-u*.d24r0 &flu-pva*.&flu.o+1d0v+1&majorkey.h16&maj3-u*.d16r0
.cel-allmaj-48-7-a &cel-pva*.&cel.d0e8h12v-9o+1&majork*.&maj3-d*.d12r0 &cel-pva*.&cel.d0e8h12v-9o+1&majork*.&maj3-d*.d12r0 &cel-pva*.&cel.d0e8h12v-9o+1&majork*.&maj3-d*.d12r0 &cel-pva*.&cel.d0e8h12v-9o+1&majork*.&maj3-d*.d12r0
.cel-allmaj-16-7-a &cel-pva*.&cel.d0e8h12v-9o+1&majork*.&maj3-d*.d8r0 &cel-pva*.&cel.d0e8h12v-9o+1&majork*.&maj3-d*.d8r0
.cel-allmaj-64-7-a &cel-allmaj-48-7-a. &cel-allmaj-16-7-a.
.cel-allmaj-64-7-b &cel.d64r0
.cel-allmaj-64-7-c &cel-pva*.&cel.d32r0 &cel.d0e16h32v-7o+1&majork*.&maj3-d*.d32r0
.cel-allmaj-64-7-d &cel-pva*.&cel.d0e16h32v-7o+1&majork*.&maj3-d*.d32r0 &cel-pva*.&cel.d32r0
.cel-allmaj-64-7-e &cel.d64r0
.cel-allmaj-64-7-f &cel-pva*.&cel.d0e16h32v-7o+1&majork*.&maj3-d*.d32r0 &cel-pva*.&cel.d0e16h32v-8o+1&majork*.&maj3-d*.d32r0
.cel-allmaj-64-7-h &cel.d64r0
.cel-allmaj-64-7-g &cel-pva*.&cel.e16v-10o+2d0h24&majorkey.&maj3-u*.d24r0 &cel-pva*.&cel.e16o+2v-10d0&majorkey.h24&maj3-u*.d24r0 &cel-pva*.&cel.e16v-10o+2d0&majorkey.h16&maj3-u*.d16r0
@                                           t0   t31  t0   t43  t31     t25  t17 t9
.fib-allmaj-64-7-a &fib.&majork*.&majoro*.v+5e8d12 t+31 t+22 t-10 t-12d4  t-6  t-8 t-8
@                                           t0      t43  t31  t17  t25  t31 t37 t43
.fib-allmaj-64-7-b &fib.&majork*.&majoro*.v+5e8d12 t-10 t-12 t-14 t-8d4 t+6 t+6 t+6
@                                           t0      t31  t17  t9   t0   t9  t17  t25
.fib-allmaj-64-7-c &fib.&majork*.&majoro*.v+5e8d12 t-22 t-14 t-8  d4t-9 t+9 t+8  t+8
@
.fi2-allmaj-32-7-a &fi2.d8r0 &fin-ran*.d0o4h4&majorkey.&maj4-u-*.d16 &fi2.d0o4h4&majorkey.&maj4-u-*.d8
.fi2-allmaj-32-7-b &fi2.d8r0 &fin-ran*.d0o4h4&majorkey.&maj4-u-*.d16 &fi2.d0o4h4&majorkey.&maj4-u-*.d4 &fi2.d0o4h4&majorkey.&maj4-u-*.d4
.fi2-allmaj-64-7-a &fi2-allmaj-32-7-*. &fi2-allmaj-32-7-*.
.fi2-allmaj-64-7-b &fi2.d0o4h4&majorkey.&maj4-u-*.d12 &fi2.d0o4h4&majorkey.&maj4-u-*.d12 &fi2.d0o4h4&majorkey.&maj4-u-*.d12 &fi2.d0o4h4&majorkey.&maj4-u-*.d12 &fi2.d0o4h4&majorkey.&maj4-u-*.d8 &fi2.d0o4h4&majorkey.&maj4-u-*.d8
.fi3-allmaj-40-7-a &fin-pva*.&fi3.v-2d4e8h24o+2&majork*.&maj3-u*.r0d0 &fi3.v-2d4e8h24o+1&majork*.&maj3-d*.d8h9 &fi3.v-2d4e8h24o+2&majork*.&maj3-u*.r0d0 &fi3.v-2d4e8h24o+1&majork*.&maj3-d*.d0r0
.fi3-allmaj-24-7-a &fi3.v-2d4e8h24o+2&majork*.&maj3-u*.r0d0 &fi3.v-2d4e8h24o+1&majork*.&maj3-d*.h9d8
.fi3-allmaj-40-7-b &fin-pva*.&fi3.v-5d4e8h24o+3&majork*.&maj3-u*.r0d0 &fi3.v-5d4e8h24o+2&majork*.&maj3-d*.d8h9 &fi3.v-5d4e8h24o+3&majork*.&maj3-u*.r0d0 &fi3.v-5d4e8h24o+2&majork*.&maj3-d*.d0r0
.fi3-allmaj-24-7-b &fi3.v-5d4e8h24o+3&majork*.&maj3-u*.r0d0 &fi3.v-5d4e8h24o+2&majork*.&maj3-d*.h9d8
.fi3-allmaj-64-7-a &fi3-allmaj-40-7-*. &fi3-allmaj-24-7-*.
@ 1922
@ all minor keys
@  utonality minor
@  1  2  3  4  5  6  7  8  1  2  3  4  5  6  7   8   1
@  0  7 14 22 31 36 41 47 53 60 67 75 84 89 94 100 105
@    +7 +7 +8 +9 +5 +5 +6 +6 +7 +7 +8 +9 +5 +5  +6  +6
@      +14   +17         +22
@  0      +22      +19
@     7      +24       +16
@       14      +22      +17
@
@    +7   +15      +19       +19
@ ratio num 1 12 6 4 3 8 12 24 1
@ ratio den 1 11 5 3 2 5 7 13 1
@ name      C D  E  F  G  A  A  B  C  D  E  F  G  A  A   B   C
@ #         1 2  3  4  5  6  7  8  1  2  3  4  5  6  7   8   9
@ absolute  0 7 14 22 31 36 41 47 53 60 67 75 84 89 94 100 106
@ steps     +7 +7 +8 +9 +5 +5 +6 +6 +7 +7 +8 +9 +5 +5  +6  +6
@ thirds a    +14   +17   +22
@ thirds b   7   +15   +19   +19
@ 1945
@ Need three versions of this section, each starting at a different point.
@ Then pick the proper point for each key, maximizing the notes in common
@ what if there was a way to match notes from one chord to the next after transposition?
@ turn down the cello, turn up the flute
.qu1 v-12
.qu2 v-8
.qu3 v-4
.qu4 v+0
.qu5 v-6
.flu-allmin-40-7-a1 &flu-pva*.&flu.v+11d4e8h5o+2&minoro*.&minork*.&qu*.&min3-u-a3*.r0d0 &flu.v+11d4e8h5&minoro*.&minork*.o+1&qu*.&min3-d-b4*.d8h9 &flu.v+11d4e8h5&minoro*.&minork*.o+1&qu*.&min3-u-a1*.r0d0
.flu-allmin-24-7-a1 &flu.v+11d4e8h5&minoro*.&minork*.&qu*.&min3-d-b2*.d0r0 &flu.v+11d4e8h5&minoro*.&minork*.o+1&qu*.&min3-u-a5*.r0d0 &flu.v+11d4e8h5&minoro*.&minork*.&qu*.&min3-d-b2*.h9d8
.flu-allmin-64-7-a1 &flu-allmin-40-7-a1. &flu-allmin-24-7-a1.
.flu-allmin-40-7-a2 &flu-pva*.&flu.v+11d4e8h5o+1&minoro*.&minork*.&qu*.&min3-u-a1*.r0d0 &flu.v+11d4e8h5&minoro*.&minork*.&qu*.&min3-d-b2*.d8h9 &flu.v+11d4e8h5o+1&minoro*.&minork*.&qu*.&min3-u-a5*.r0d0
.flu-allmin-24-7-a2 &flu.v+11d4e8h5o-1&minoro*.&minork*.&qu*.&min3-d-b7*.d0r0 &flu.v+11d4e8h5o+1&minoro*.&minork*.&qu*.&min3-u-a3*.r0d0 &flu.v+11d4e8h5&minoro*.&minork*.o-1&qu*.&min3-d-b7*.h9d8
.flu-allmin-64-7-a2 &flu-allmin-40-7-a2. &flu-allmin-24-7-a2.
.flu-allmin-40-7-a3 &flu-pva*.&flu.v+11d4e8h5o+1&minoro*.&minork*.&qu*.&min3-u-a5*.r0d0 &flu.v+11d4e8h5&minoro*.&minork*.o-1&qu*.&min3-d-b7*.d8h9 &flu.v+11d4e8h5&minoro*.&minork*.o+1&qu*.&min3-u-a3*.r0d0
.flu-allmin-24-7-a3 &flu.v+11d4e8h5&minoro*.&minork*.&qu*.&min3-d-b4*.d0r0 &flu.v+11d4e8h5&minoro*.&minork*.&qu*.&min3-u-a1*.r0d0 &flu.v+11d4e8h5&minoro*.&minork*.&qu*.&min3-d-b4*.h9d8
.flu-allmin-64-7-a3 &flu-allmin-40-7-a3. &flu-allmin-24-7-a3.
.flu-allmin-64-7-g1 &flu-pva*.&flu.e16v-5o+1d0h24&minoro*.&minorkey.&qu*.&min3-u-b2*.d24r0 &flu-pva*.&flu.e16o+1v-5d0&minoro*.&minorkey.h24&qu*.&min3-u-a1*.d24r0 &flu-pva*.&flu.e16v-5o+1d0&minoro*.&minorkey.h16&qu*.&min3-u-b7*.d16r0
.flu-allmin-64-7-g2 &flu-pva*.&flu.e16v-5o+1d0h24&minoro*.&minorkey.&qu*.&min3-u-b7*.d24r0 &flu-pva*.&flu.e16o+1v-5d0&minoro*.&minorkey.h24&qu*.&min3-u-a5*.d24r0 &flu-pva*.&flu.e16v-5o+1d0&minoro*.&minorkey.h16&qu*.&min3-u-b4*.d16r0
.flu-allmin-64-7-g3 &flu-pva*.&flu.e16v-5o+1d0h24&minoro*.&minorkey.&qu*.&min3-u-b4*.d24r0 &flu-pva*.&flu.e16o+1v-5d0&minoro*.&minorkey.h24&qu*.&min3-u-a3*.d24r0 &flu-pva*.&flu.e16v-5o+0d0&minoro*.&minorkey.h16&qu*.&min3-u-b2*.d16r0
.cel-allmin-40-7-a1 &cel-pva*.&cel.v-2d4e8h5o+3&minoro*.&minork*.&qu*.&min3-u-a3*.r0d0 &cel.v-2d4e8h5&minoro*.&minork*.o+2&qu*.&min3-d-b4*.d8h9 &cel.v-2d4e8h5&minoro*.&minork*.o+2&qu*.&min3-u-a1*.r0d0
.cel-allmin-24-7-a1 &cel.v-2d4e8h5&minoro*.&minork*.o+1&qu*.&min3-d-b2*.d0r0 &cel.v-2d4e8h5&minoro*.&minork*.o+2&qu*.&min3-u-a5*.r0d0 &cel.v-2d4e8h5&minoro*.&minork*.&qu*.&min3-d-b2*.h9d8
.cel-allmin-64-7-a1 &cel-allmin-40-7-a1. &cel-allmin-24-7-a1.
.cel-allmin-40-7-a2 &cel-pva*.&cel.v-2d4e8h5&minoro*.&minork*.o+2&qu*.&min3-u-a1*.r0d0 &cel.v-2d4e8h5&minoro*.&minork*.o+1&qu*.&min3-d-b2*.d8h9 &cel.v-2d4e8h5&minoro*.&minork*.o+2&qu*.&min3-u-a5*.r0d0
.cel-allmin-24-7-a2 &cel.v-2d4e8h5&minoro*.&minork*.&qu*.&min3-d-b7*.d0r0 &cel.v-2d4e8h5o+2&minoro*.&minork*.&qu*.&min3-u-a3*.r0d0 &cel.v-2d4e8h5&minoro*.&minork*.o-1&qu*.&min3-d-b7*.h9d8
.cel-allmin-64-7-a2 &cel-allmin-40-7-a2. &cel-allmin-24-7-a2.
.cel-allmin-40-7-a3 &cel-pva*.&cel.v-2d4e8h5&minoro*.&minork*.o+2&qu*.&min3-u-a5*.r0d0 &cel.v-2d4e8h5&minoro*.&minork*.&qu*.&min3-d-b7*.d8h9 &cel.v-2d4e8h5&minoro*.&minork*.o+2&qu*.&min3-u-a3*.r0d0
.cel-allmin-24-7-a3 &cel.v-2d4e8h5&minoro*.&minork*.o+1&qu*.&min3-d-b4*.d0r0 &cel.v-2d4e8h5&minoro*.&minork*.o+1&qu*.&min3-u-a1*.r0d0 &cel.v-2d4e8h5&minoro*.&minork*.o+1&qu*.&min3-d-b4*.h9d8
.cel-allmin-64-7-a3 &cel-allmin-40-7-a3. &cel-allmin-24-7-a3.
.cel-allmin-64-7-g1 &cel-pva*.&cel.e16v-8o+2d0h24&minoro*.&minorkey.&qu*.&min3-u-a3*.d24r0 &cel-pva*.&cel.e16v-10o+1d0&minoro*.&minorkey.h24&qu*.&min3-u-b2*.d24r0 &cel-pva*.&cel.e16v-10o+1d0&minoro*.&minorkey.h16&qu*.&min3-u-a1*.d16r0
.cel-allmin-64-7-g2 &cel-pva*.&cel.e16v-8o+1d0h24&minoro*.&minorkey.&qu*.&min3-u-a1*.d24r0 &cel-pva*.&cel.e16v-10o+1d0&minoro*.&minorkey.h24&qu*.&min3-u-b7*.d24r0 &cel-pva*.&cel.e16v-10o+1d0&minoro*.&minorkey.h16&qu*.&min3-u-a5*.d16r0
.cel-allmin-64-7-g3 &cel-pva*.&cel.e16v-8o+1d0h24&minoro*.&minorkey.&qu*.&min3-u-a5*.d24r0 &cel-pva*.&cel.e16v-10o+1d0&minoro*.&minorkey.h24&qu*.&min3-u-b4*.d24r0 &cel-pva*.&cel.e16v-12o+1d0&minoro*.&minorkey.h16&qu*.&min3-u-a3*.d16r0
@                                           t0      t31  t0   t41  t31 t22 t14 t7
.fib-allmin-64-7-a &fib.&minork*.&minoro*.v+5e8d12 t+31 t+22 t-12 d4t-10 t-9 t-8 t-7
@                                           t0      t41  t31  t14  t22  t31 t36 t41
.fib-allmin-64-7-b &fib.&minork*.&minoro*.v+5e8d12 t-12 t-10 t-17 t+8d4 t+9 t+5 t+5
@                                           t0      t31  t14  t7   t0   t7  t14  t22
.fib-allmin-64-7-c &fib.&minork*.&minoro*.v+5e8d12 t-22 t-17 t-7  d4t-7 t+7 t+7  t+8
@
.fi2-allmin-32-7-a &fi2.d8r0 &fin-ran*.d0o+2h4&minoro*.&minorkey.&min4-u-*.d16 &fi2.d0o+2h4&minoro*.&minorkey.&min4-u-*.d8
.fi2-allmin-32-7-b &fi2.d8r0 &fin-ran*.d0o+2h4&minoro*.&minorkey.&min4-u-*.d16 &fi2.d0o+2h4&minoro*.&minorkey.&min4-u-*.d4 &fi2.d0o+2h4&minoro*.&minorkey.&min4-u-*.d4
.fi2-allmin-64-7-a &fi2-allmin-32-7-*. &fi2-allmin-32-7-*.
.fi2-allmin-48-7-b &fi2.d0o+2h4&minoro*.&minorkey.&min4-u-*.d12 &fi2.d0o+2h4&minoro*.&minorkey.&min4-u-*.d12 &fi2.d0o4h4&minoro*.&minorkey.&min4-u-*.d12 &fi2.d0o+2h4&minoro*.&minorkey.&min4-u-*.d12
.fi2-allmin-16-7-b &fi2.d0o+2h4&minoro*.&minorkey.&min4-u-*.d8 &fi2.d0o+2h4&minoro*.&minorkey.&min4-u-*.d8
.fi2-allmin-64-7-b &fi2-allmin-48-7-b. &fi2-allmin-16-7-b.
.fi3-allmin-40-7-a1 &fin-pva*.&fi3.v+3d4e8h5o+3&minoro*.&minork*.&qu*.&min3-u-a3*.r0d0 &fi3.v+3d4e8h5&minoro*.o+2&minork*.&qu*.&min3-d-b4*.d8h9 &fi3.v+3d4e8h5&minoro*.&minork*.o+2&qu*.&min3-u-a1*.r0d0
.fi3-allmin-24-7-a1 &fi3.v+3d4e8h5&minoro*.&minork*.o+1&qu*.&min3-d-b2*.d0r0 &fi3.v+3d4e8h5&minoro*.o+2&minork*.&qu*.&min3-u-a5*.r0d0 &fi3.v+3d4e8h5&minoro*.&minork*.o+1&qu*.&min3-d-b2*.h9d8
.fi3-allmin-64-7-a1 &fi3-allmin-40-7-a1. &fi3-allmin-24-7-a1.
.fi3-allmin-40-7-a2 &fin-pva*.&fi3.v+3d4e8h5o+2&minoro*.&minork*.&qu*.&min3-u-a1*.r0d0 &fi3.v+3d4e8h5&minoro*.&minork*.o+1&qu*.&min3-d-b2*.d8h9 &fi3.v+3d4e8h5o+2&minoro*.&minork*.&qu*.&min3-u-a5*.r0d0
.fi3-allmin-24-7-a2 &fi3.v+3d4e8h5&minoro*.&minork*.&qu*.&min3-d-b7*.d0r0 &fi3.v+3d4e8h5o+2&minoro*.&minork*.&qu*.&min3-u-a3*.r0d0 &fi3.v+3d4e8h5&minoro*.&minork*.&qu*.&min3-d-b7*.h9d8
.fi3-allmin-64-7-a2 &fi3-allmin-40-7-a2. &fi3-allmin-24-7-a2.
.fi3-allmin-40-7-a3 &fin-pva*.&fi3.v+3d4e8h5o+2&minoro*.&minork*.&qu*.&min3-u-a5*.r0d0 &fi3.v+3d4e8h5&minoro*.&minork*.&qu*.&min3-d-b7*.d8h9 &fi3.v+3d4e8h5&minoro*.&minork*.o+2&qu*.&min3-u-a3*.r0d0
.fi3-allmin-24-7-a3 &fi3.v+3d4e8h5&minoro*.&minork*.o+1&qu*.&min3-d-b4*.d0r0 &fi3.v+3d4e8h5&minoro*.&minork*.o+1&qu*.&min3-u-a1*.r0d0 &fi3.v+3d4e8h5&minoro*.&minork*.o+1&qu*.&min3-d-b4*.h9d8
.fi3-allmin-64-7-a3 &fi3-allmin-40-7-a3. &fi3-allmin-24-7-a3.
.fi3-allmin-64-7-g1 &fin-pva*.&fi3.e16v+1o+2d0h24&minoro*.&minorkey.&qu*.&min3-u-a3*.d24r0 &fin-pva*.&fi3.e16v+1o+1d0&minoro*.&minorkey.h24&qu*.&min3-u-b2*.d24r0 &fin-pva*.&fi3.e16v+1o+1d0&minoro*.&minorkey.h16&qu*.&min3-u-a1*.d16r0
.fi3-allmin-64-7-g2 &fin-pva*.&fi3.e16v+1o+1d0h24&minoro*.&minorkey.&qu*.&min3-u-a1*.d24r0 &fin-pva*.&fi3.e16v+1o+1d0&minoro*.&minorkey.h24&qu*.&min3-u-b7*.d24r0 &fin-pva*.&fi3.e16v+1o+1d0&minoro*.&minorkey.h16&qu*.&min3-u-a5*.d16r0
.fi3-allmin-64-7-g3 &fin-pva*.&fi3.e16v+1o+1d0h24&minoro*.&minorkey.&qu*.&min3-u-a5*.d24r0 &fin-pva*.&fi3.e16v+1o+1d0&minoro*.&minorkey.h24&qu*.&min3-u-b4*.d24r0 &fin-pva*.&fi3.e16v-12o+1d0&minoro*.&minorkey.h16&qu*.&min3-u-a3*.d16r0
.flu-pva-1 p10
.fl2-pva-1 p33
.fin-pva-1 p33
.dsp-pva-1 p27
.cel-pva-1 p33
@ how loud the cello
.cel-vel1 &all-vel*.v+3
@ intro circle - may need to prime the pump with something more interesting than random repetition. maybe more variety?
.alla-min-0 &fin-pva*.&fib-allmin-64-3-*. &fin-pva*.&fi2-allmin-64-3-*. &fin-pva*.&fi3-allmin-64-4-d.
.allb-min-0 &flu-pva*.&flu-allmin-64-3-a. &cel-pva*.&cel-allmin-64-3-a.
.allc-min-0 &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-1-*. &dsp-pva*.&dspring32-1-*.
.all-min-0a &alla-min-0. &allb-min-0. &allc-min-0.
.alla-min-1 &fin-pva*.&fib-allmin-64-3-*. &fin-pva*.&fi2-allmin-64-3-*. &fin-pva*.&fi3-allmin-64-4-d.
.allb-min-1 &flu-pva*.&flu-allmin-64-3-*. &cel-pva*.&cel-allmin-64-3-*.
.allc-min-1 &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-1-*. &dsp-pva*.&dspring32-1-*.
.all-min-1a &alla-min-1. &allb-min-1. &allc-min-1.
@ 1523
@ active counter to the primary melody in minor
@ first measure
.alla-min-2a &fin-pva*.&fib-allmin-64-1-*. &fin-pva*.&fi2-allmin-32-1-*. &fin-pva*.&fi2-allmin-32-1-*. &fin-pva*.&fi3-allmin-32-1-*. &fin-pva*.&fi3-allmin-32-1-*.
.allb-min-2a &flu-pva*.&flu-allmin-64-1-a. &cel-pva*.&cel-allmin-64-0-a.
.allc-min-2a &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-1-*. &dsp-pva*.&dspring32-1-*.
.all-min-2a &alla-min-2a. &allb-min-2a. &allc-min-2a.
@ subsequent measures
@ 1538
.alla-min-2b &fin-pva*.&fib-allmin-64-1-*. &fin-pva*.&fi2-allmin-32-1-*. &fin-pva*.&fi2-allmin-32-1-*. &fin-pva*.&fi3-allmin-32-1-*. &fin-pva*.&fi3-allmin-32-1-*.
.allb-min-2b &flu-pva*.&flu-allmin-64-1-*. &cel-pva*.&cel-allmin-64-1-*.
.allc-min-2b &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-1-*. &dsp-pva*.&dspring32-1-*.
.all-min-2b &alla-min-2b. &allb-min-2b. &allc-min-2b.
.allb-min-2c &flu-pva*.&flu-allmin-64-5-*. &cel-pva*.&cel-allmin-64-5-*.
.all-min-2c &alla-min-2b. &allb-min-2c. &allc-min-2b.
@ initial major key vamp
.alla-maj-1a &fin-pva*.&fib-allmaj-64-3-*. &fin-pva*.&fi2-allmaj-32-4-*. &fin-pva*.&fi2-allmaj-32-4-*. &fin-pva*.&fi3-allmaj-64-5-*.
.allb-maj-1a &flu-pva*.&flu-allmaj-64-4-*. &cel-pva*.&cel-allmaj-64-4-*.
.allc-maj-1a &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-1-*. &dsp-pva*.&dspring32-1-*.
.all-maj-1a &alla-maj-1a. &allb-maj-1a. &allc-maj-1a.
@ melody
.alla-maj-2x &majorkey.&flu-allmaj-32-1-a. &fi2.d0o4h64&majorkey.t+17 t+26 t+19d24 d0o4h48&majorkey.t+9 t+22 t+22d40 d0a255r0 &cel.d64r0 &fib.&majorkey.o-1d64  &fi3.d64r0 &dsp.d64r0 &ds2.d64r0
.alla-maj-2a &majorkey.&flu-allmaj-64-1-a. &cel-pva*.&cel-allmaj-64-1-a. &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-1-*. &dsp-pva*.&dspring32-1-*.
.alla-maj-2b &majorkey.&flu-allmaj-64-1-b. &cel-pva*.&cel-allmaj-64-1-b. &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-1-*. &dsp-pva*.&dspring32-1-*.
.alla-maj-2c &majorkey.&flu-allmaj-64-1-c. &cel-pva*.&cel-allmaj-64-1-c. &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-1-*. &dsp-pva*.&dspring32-1-*.
.alla-maj-2d &majorkey.&flu-allmaj-64-1-d. &cel-pva*.&cel-allmaj-64-1-d. &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-1-*. &dsp-pva*.&dspring32-1-*.
.alla-maj-2e &majorkey.&flu-allmaj-64-1-e. &cel-pva*.&cel-allmaj-64-1-e. &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-1-*. &dsp-pva*.&dspring32-1-*.
.alla-maj-2f &majorkey.&flu-allmaj-64-1-f. &cel-pva*.&cel-allmaj-64-1-f. &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-1-*. &dsp-pva*.&dspring32-1-*.
.alla-maj-2g &majorkey.&flu-allmaj-64-1-g. &cel-pva*.&cel-allmaj-64-1-g. &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-1-*. &dsp-pva*.&dspring32-1-*.
.alla-maj-2h &majorkey.&flu-allmaj-64-1-h. &cel-pva*.&cel-allmaj-64-1-h. &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-1-*. &dsp-pva*.&dspring32-1-*.
.alla-maj-2i &majorkey.&flu-allmaj-64-1-i. &cel-pva*.&cel-allmaj-64-1-i. &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-1-*. &dsp-pva*.&dspring32-1-*.
@ 1568
.alla-maj-3a &majorkey.&flu-allmaj-64-3-*. &cel-pva*.&cel-allmaj-64-3-*. &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-1-*. &dsp-pva*.&dspring32-1-*.
@ incrasing complexity
.allb-maj-2 &fin-pva*.&fib-allmaj-64-1-*. &fin-pva*.&fi2-allmaj-32-1-*. &fin-pva*.&fi2-allmaj-32-1-*. &fin-pva*.&fi3-allmaj-32-4-*. &fin-pva*.&fi3-allmaj-32-4-*.
.allb-maj-3 &fin-pva*.&fib-allmaj-64-3-*. &fin-pva*.&fi2-allmaj-32-4-*. &fin-pva*.&fi2-allmaj-32-4-*. &fin-pva*.&fi3-allmaj-32-4-*. &fin-pva*.&fi3-allmaj-32-4-*.
.allb-maj-4 &fin-pva*.&fib-allmaj-64-4-*. &fin-pva*.&fi2-allmaj-32-4-*. &fin-pva*.&fi2-allmaj-32-4-*. &fin-pva*.&fi3-allmaj-32-1-*. &fin-pva*.&fi3-allmaj-32-1-*.
.allb-maj-7 &fin-pva*.&fib-allmaj-64-7-*. &fin-pva*.&fi2-allmaj-64-7-*. &fin-pva*.&fi3-allmaj-64-7-*.
.alla-maj-7 &majorkey.&flu-allmaj-64-7-a. &cel-pva*.&cel-allmaj-64-7-*. &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-1-*. &dsp-pva*.&dspring32-1-*.
.alla-maj-8 &majorkey.&flu-allmaj-64-7-b. &cel-pva*.&cel-allmaj-64-7-g. &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-1-*. &dsp-pva*.&dspring32-1-*.
@ 1631
@ minor
@ vamp in minor
.alla-min-7-1 &minorkey.&flu-allmin-64-7-a1. &cel-pva*.&cel-allmin-64-7-a1. &fin-pva*.&fi3-allmin-64-7-a1*.
.alla-min-7-2 &minorkey.&flu-allmin-64-7-a2. &cel-pva*.&cel-allmin-64-7-a2. &fin-pva*.&fi3-allmin-64-7-a2*.
.alla-min-7-3 &minorkey.&flu-allmin-64-7-a3. &cel-pva*.&cel-allmin-64-7-a3. &fin-pva*.&fi3-allmin-64-7-a3*.
@ melody
.alla-min-8-1 &minorkey.&flu-allmin-64-7-g1. &cel-pva*.&cel-allmin-64-7-g1. &fin-pva*.&fi3-allmin-64-7-g1*.
.alla-min-8-2 &minorkey.&flu-allmin-64-7-g2. &cel-pva*.&cel-allmin-64-7-g2. &fin-pva*.&fi3-allmin-64-7-g2*.
.alla-min-8-3 &minorkey.&flu-allmin-64-7-g3. &cel-pva*.&cel-allmin-64-7-g3. &fin-pva*.&fi3-allmin-64-7-g3*.
@ chords
.alla-min-9-1 &minorkey.&flu-allmin-64-7-a1. &cel-pva*.&cel-allmin-64-7-g1. &fin-pva*.&fi3-allmin-64-7-a1*.
.alla-min-9-2 &minorkey.&flu-allmin-64-7-a2. &cel-pva*.&cel-allmin-64-7-a2. &fin-pva*.&fi3-allmin-64-7-g2*.
.alla-min-9-3 &minorkey.&flu-allmin-64-7-g3. &cel-pva*.&cel-allmin-64-7-a3. &fin-pva*.&fi3-allmin-64-7-a3*.
@ melody alternating with chords
.allb-min-7-1 &fin-pva*.&fib-allmin-64-7-*. &fin-pva*.&fi2-allmin-64-7-*. &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-1-*. &dsp-pva*.&dspring32-1-*.
.allb-min-7-2 &fin-pva*.&fib-allmin-64-7-*. &fin-pva*.&fi2-allmin-64-7-*. &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-1-*. &dsp-pva*.&dspring32-1-*.
.allb-min-7-3 &fin-pva*.&fib-allmin-64-7-*. &fin-pva*.&fi2-allmin-64-7-*. &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-2-*. &dsp-pva*.&dspring32-1-*. &dsp-pva*.&dspring32-1-*.
.all-min-8-1-a &alla-min-7-1. &allb-min-7-1.
.all-min-8-2-a &alla-min-7-2. &allb-min-7-2.
.all-min-8-3-a &alla-min-7-3. &allb-min-7-3.
.all-min-8-1-b &alla-min-8-1. &allb-min-7-1.
.all-min-8-2-b &alla-min-8-2. &allb-min-7-2.
.all-min-8-3-b &alla-min-8-3. &allb-min-7-3.
.all-min-8-1-c &alla-min-9-1. &allb-min-7-1.
.all-min-8-2-c &alla-min-9-2. &allb-min-7-2.
.all-min-8-3-c &alla-min-9-3. &allb-min-7-3.
@ major
.all-maj-2x &alla-maj-2x.
.all-maj-2a &alla-maj-2a. &allb-maj-2.
.all-maj-2b &alla-maj-2b. &allb-maj-2.
.all-maj-2c &alla-maj-2c. &allb-maj-2.
.all-maj-2d &alla-maj-2d. &allb-maj-2.
.all-maj-2e &alla-maj-2e. &allb-maj-2.
.all-maj-2f &alla-maj-2f. &allb-maj-2.
.all-maj-2g &alla-maj-2g. &allb-maj-2.
.all-maj-2h &alla-maj-2h. &allb-maj-2.
.all-maj-2i &alla-maj-2i. &allb-maj-2.
.all-maj-3x &alla-maj-2x.
.all-maj-3a &alla-maj-2a. &allb-maj-4.
.all-maj-3b &alla-maj-2b. &allb-maj-4.
.all-maj-3c &alla-maj-2c. &allb-maj-4.
.all-maj-3d &alla-maj-2d. &allb-maj-4.
.all-maj-3e &alla-maj-2e. &allb-maj-4.
.all-maj-3f &alla-maj-2f. &allb-maj-4.
.all-maj-3g &alla-maj-2g. &allb-maj-4.
.all-maj-3h &alla-maj-2h. &allb-maj-4.
.all-maj-3i &alla-maj-2i. &allb-maj-4.
.all-maj-4a &alla-maj-3a. &allb-maj-4.
.all-maj-5a &alla-maj-3a. &allb-maj-3.
@ music box arpeggio
.all-maj-6a &fib.d64h256&majorkey.v+4o-1 &fin-pva*.&fi3-allmaj-64-6-d. &fin-pva*.&fi2-allmaj-64-6-d. &flu-pva*.&flu-allmaj-64-6-*. &cel-pva*.&cel-allmaj-64-6-*. &allc-maj-1a.
@
.all-maj-7a &allb-maj-4. &allb-maj-1a. &allc-maj-1a.
.all-maj-8a &alla-maj-7. &allb-maj-7.
.all-maj-8b &alla-maj-8. &allb-maj-7.
@
@ start of the piece
@
@ a little quiet to start
@ roaming the circle
.dsp-ran-1 r0
.cel-ran-1 r0
.flu-ran-1 r0
.ce2-ran-1 r0
.dsx-ran r2
&flu.d16r0 &fib.d16r0 &fi2.d16r0 &fi3.d16r0 &cel.d16r0 &ds2.d16r0 &dsp.d16r0 &vel.d16a200
.minorkey t5
.minoroct o-0
&all-min-0a.
&vel.d64a205 d0
.minorkey t27
.minoroct o-0
&all-min-1a.
&vel.d64a210 d0
.dsp-ran-1 r8
.dsx-ran-1 r4
.cel-ran-1 r4
.flu-ran-1 r4
.ce2-ran-1 r2
.minorkey t49
.minoroct o-1
&all-min-1a.
&vel.d64a215 d0
.minorkey t18
.minoroct o-0
&all-min-1a.
&vel.d64a220 d0
.minorkey t40
.minoroct o-1
.dsp-ran-1 r12
.cel-ran-1 r8
.flu-ran-1 r10
.ce2-ran-1 r12
.dsx-ran r8
&all-min-1a.
&vel.d64a225 d0
.minorkey t9
.minoroct o-0
&all-min-1a.
&vel.d64a230 d0
.minorkey t31
.minoroct o-1
&all-min-1a.
&vel.d64a245 d0
.dsp-ran-1 r15
.cel-ran-1 r16
.flu-ran-1 r16
.ce2-ran-1 r12
.dsx-ran r8
@ vamp at very low intensity
@ what key to start:
.majorkey t0
.majoroct o+0
&all-maj-1a. &vel.d64a255
&all-maj-1a. &vel.d64a255
&all-maj-1a. &vel.d64a255
&all-maj-1a. &vel.d64a255
@
@ 0:22 intro melody
@
&all-maj-2x. &vel.d64a255
&all-maj-2a. &vel.d64a255
&all-maj-2b. &vel.d64a255
&all-maj-2c. &vel.d64a255
&all-maj-2d. &vel.d64a255
&flu-allmaj-32-1-e.
&all-maj-2e. &vel.d64a255
&all-maj-2f. &vel.d64a255
&all-maj-2g. &vel.d64a255
&all-maj-2h. &vel.d64a255
&all-maj-2i. &vel.d64a255
@
@ 0:42 intro melody with more active bass
@ - would it be nice to vary the start times of the back beat finger piano?
&all-maj-3x. &vel.d64a255
&all-maj-3a. &vel.d64a255
&all-maj-3b. &vel.d64a255
&all-maj-3c. &vel.d64a255
&all-maj-3d. &vel.d64a255
&flu-allmaj-32-1-e.
&all-maj-3e. &vel.d64a255
&all-maj-3f. &vel.d64a255
&all-maj-3g. &vel.d64a255
&all-maj-3h. &vel.d64a255
&all-maj-3i. &vel.d64a255
@  :58 Bridge
@ e minor
.flu-pva-1 p33
.cel-pva-1 p33
.fin-pva-1 p22
.dsp-pva-1 p25
.ds2-pva-1 p28
.dsx-ran r8
.minorkey t17
.minoroct o+0
@ bridge
&all-min-2a. &vel.a255d64
&all-min-2b. &vel.a255d64
@ a minor
.minorkey t39
.minoroct o-1
&all-min-2b. &vel.a255d64
&all-min-2b. &vel.a255d64
@ d minor
.minoroct o+0
.minorkey t8
&all-min-2b. &vel.a255d64
&all-min-2b. &vel.a255d64
.flu-pva-1 p2
.cel-pva-1 p2
.fin-pva-1 p2
@ G minor up by one step each measure.
@ cut way back on the notes to reduce the density
.dsp-ran-1 r8
.dsx-ran-1 r4
.cel-ran-1 r4
.flu-ran-1 r4
.ce2-ran-1 r2
.minoroct o-1
.minorkey t30
&all-min-2c. &vel.a200d64 a255d0
.flu-pva-1 p28
.cel-pva-1 p28
.fin-pva-1 p25
@ G minor
.minoroct o-1
.minorkey t31
&all-min-2c. &vel.a205d64 a255d0
@ G minor
.minoroct o-1
.minorkey t32
&all-min-2c. &vel.a210d64 a255d0
@ G minor
.dsp-ran-1 r12
.cel-ran-1 r8
.flu-ran-1 r10
.ce2-ran-1 r12
.dsx-ran r8
.minoroct o-1
.minorkey t33
&all-min-2c. &vel.a215d64 a255d0
@ G minor
.minoroct o-1
.minorkey t32
&all-min-2c. &vel.a220d64 a255d0
@ G minor
.minoroct o-1
.minorkey t31
&all-min-2c. &vel.a225d64 a255d0
@ going low
@ back to full density again
.dsp-ran-1 r15
.cel-ran-1 r16
.flu-ran-1 r16
.ce2-ran-1 r12
.dsx-ran r8
.minoroct o-1
.minorkey t30
&all-min-2c. &vel.a245d64 a255d0
.majorkey t0
.majoroct o+0
@ 1:28 back to the melody
&all-maj-3x. &vel.d64a255
&all-maj-3a. &vel.d64a255
&all-maj-3b. &vel.d64a255
&all-maj-3c. &vel.d64a255
&all-maj-3d. &vel.d64a255
&flu-allmaj-32-1-e.
.majorkey t1
.majoroct o+1
@ 1:35 variations with sliding flute and cello parts
.cel-ran-1 r15
.flu-ran-1 r15
@ 1982
&all-maj-4a. &vel.d64a255
.fin-z1 z10
.flu-pva-1 p2
.cel-pva-1 p2
.fin-pva-1 p2
.majorkey t2
&all-maj-4a. &vel.d64a255
.majorkey t3
&all-maj-4a. &vel.d64a255
.majorkey t2
&all-maj-4a. &vel.d64a255
.majorkey t1
&all-maj-4a. &vel.d64a255
.flu-pva-1 p33
.cel-pva-1 p33
.fin-pva-1 p19
.majorkey t0
&all-maj-4a. &vel.d64a255
.majorkey t1
&all-maj-4a. &vel.d64a255
.majorkey t2
&all-maj-4a. &vel.d64a255
.majorkey t3
&all-maj-4a. &vel.d64a255
.majorkey t2
&all-maj-4a. &vel.d64a255
.majorkey t1
&all-maj-4a. &vel.d64a255
.majorkey t0
&all-maj-4a. &vel.d64a255
.flu-pva-1 p26
.cel-pva-1 p26
.fin-pva-1 p33
.majorkey t0
&all-maj-5a. &vel.d64a255
.majorkey t1
&all-maj-5a. &vel.d64a255
.majorkey t2
&all-maj-5a. &vel.d64a255
.majorkey t3
&all-maj-5a. &vel.d64a255
.majorkey t2
&all-maj-4a. &vel.d64a255
.majorkey t1
&all-maj-4a. &vel.d64a255
.majorkey t0
.majoroct o+0
&all-maj-4a. &vel.d64a255
.fin-pva-1 p33
@
@ 2:10 just a vamp with crescendos
&all-maj-7a. &vel.d64a140 d0a205
&all-maj-7a. &vel.d64a140 d0a205
.majorkey t1
&all-maj-7a. &vel.d64a140 d0a200
.majorkey t2
&all-maj-7a. &vel.d64a140 d0a200
.majorkey t3
&all-maj-7a. &vel.d64a140 d0a200
.majorkey t2
&all-maj-7a. &vel.d64a140 d0a200
.majorkey t1
&all-maj-7a. &vel.d64a140 d0a200
.majorkey t0
&all-maj-7a. &vel.d64a140 d0a201
.dsp-ran-1 r1
.dsx-ran r1
@ 2:30 music box arpeggio
&all-maj-6a. &vel.d64a140 d0a255
&all-maj-6a. &vel.d64a200
.majorkey t1
&all-maj-6a. &vel.d64a255
.majorkey t2
&all-maj-6a. &vel.d64a255
.majorkey t1
&all-maj-6a. &vel.d64a255
.majorkey t0
&all-maj-6a. &vel.d64a255
&all-maj-6a. &vel.d64a255
&all-maj-6a. &vel.d64a255
.dsp-ran-1 r15
.dsx-ran r14
@ vamp away at much higher energy
.cel-ran-1 r12
.flu-ran-1 r12
&all-maj-8a. &vel.d64a140 a205d0
&all-maj-8a. &vel.d64a140 a205d0
&all-maj-8a. &vel.d64a140 a205d0
&all-maj-8a. &vel.d64a140 a205d0
&all-maj-8a. &vel.d64a140 a205d0
&all-maj-8a. &vel.d64a140 a205d0
&all-maj-8a. &vel.d64a140 a205d0
.cel-ran-1 r14
.flu-ran-1 r14
&all-maj-8a. &vel.d64a140 a205d0
.flu-pva-1 p2
.fin-pva-1 p2
.cel-pva-1 p2
&all-maj-8a. &vel.d64a140 a205d0
&all-maj-8a. &vel.d64a140 a205d0
&all-maj-8a. &vel.d64a140 a205d0
.flu-pva-1 p18
.fin-pva-1 p18
.cel-pva-1 p33
&all-maj-8a. &vel.d64a140 a205d0
&all-maj-8a. &vel.d64a140 a205d0
&all-maj-8a. &vel.d64a140 a205d0
&all-maj-8a. &vel.d64a140 a205d0
.flu-pva-1 p23
.cel-pva-1 p23
&all-maj-8a. &vel.d64a140 a205d0
&all-maj-8a. &vel.d64a140 a205d0
&all-maj-8a. &vel.d64a140 a205d0
.cel-ran-1 r16
.flu-ran-1 r16
.fin-pva-1 p23
@ held chords that change every few measures
&all-maj-8b. &vel.d64a140 a255d0
&all-maj-8b. &vel.d64a140 a255d0
&all-maj-8b. &vel.d64a140 a255d0
&all-maj-8b. &vel.d64a140 a255d0
.flu-pva-1 p2
.cel-pva-1 p2
&all-maj-8a. &vel.d64a140 a255d0
&all-maj-8a. &vel.d64a140 a255d0
&all-maj-8a. &vel.d64a140 a255d0
.fin-pva-1 p2
&all-maj-8b. &vel.d64a140 a255d0
&all-maj-8b. &vel.d64a140 a235d0
.majoroct o+0
.majorkey t0
.dsp-ran-1 r15
.dsx-ran r14
&all-maj-8b. &vel.d64a140 a225d0
&all-maj-8b. &vel.d64a140 a200d0
@ new circle of fourths
@ This needs to start at a more familiar place. Eb is just too wierd.
@
@   17 39 08 30 52 21 43 12 34 03 25 47
@   16 38 07 29 51 20 42 11 33 02 24 46
@   15 37 06 28 50 19 41 10 32 01 23 45
@   14 36
@   05 27 49 18 40 09 31
@   00 22 44 13 35 04 26 48
.fin-ran-1 r16
.cel-ran-1 r4
.flu-ran-1 r4
.dsp-ran-1 r8
.dsx-ran r16
.flu-pva-1 p2
.fin-pva-1 p2
.cel-pva-1 p2
.pva-all p2
@ just a quick pause for the cause
@                                         17   43    9
&flu-allmaj-64-4-a. &fi2.v+6d0o4h64&majorkey.t+17 t+26 t+19d24 d0o4h48&majorkey.t+9 t+22 t+22d40 d0a255r0 &cel.d64r0 &fib.&majorkey.o-1d64  &fi3.d64r0 &dsp.d64r0 &ds2.d64r0 &vel.d64a200 d0a30
.minoroct o-1
.minorkey t36
.dsx-ran r3
@  go a little crazy on this one
&pva-all.&all-min-8-1*.a30 &vel.d64a140
.flu-pva-1 p33
.fin-pva-1 p33
.cel-pva-1 p33
.minoroct o+0
.minorkey t5
.cel-ran-1 r6
.flu-ran-1 r6
&pva-all.&all-min-8-1*.a255 &vel.d64a140
.minoroct o+0
.minorkey t27
.cel-ran-1 r8
.flu-ran-1 r8
&pva-all.&all-min-8-2*.a255 &vel.d64a140
.minoroct o-1
.minorkey t49
.cel-ran-1 r10
.flu-ran-1 r10
&pva-all.&all-min-8-1*.a255 &vel.d64a140
.minoroct o+0
.minorkey t18
.cel-ran-1 r12
.flu-ran-1 r12
&pva-all.&all-min-8-2*.a255 &vel.d64a140
.minoroct o-1
.minorkey t40
.cel-ran-1 r14
.flu-ran-1 r14
&pva-all.&all-min-8-3*.a255 &vel.d64a140
.minoroct o+0
.minorkey t9
.cel-ran-1 r16
.flu-ran-1 r16
&pva-all.&all-min-8-1*.a255 &vel.d64a140
.minoroct o-1
.minorkey t31
&pva-all.&all-min-8-2*.a255 &vel.d64a140
.minoroct o+0
.minorkey t5
&pva-all.&all-min-8-1*.a255 &vel.d64a140
.minoroct o+0
.minorkey t27
&pva-all.&all-min-8-3*.a255 &vel.d64a140
.minoroct o+0
.minorkey t49
&pva-all.&all-min-8-3*.a255 &vel.d64a140
.minoroct o-1
.minorkey t40
&pva-all.&all-min-8-1*.a255 &vel.d64a140
.minoroct o+0
.minorkey t18
&pva-all.&all-min-8-2*.a255 &vel.d64a140
.minoroct o-1
.minorkey t40
&pva-all.&all-min-8-1*.a255 &vel.d64a140
.minoroct o+0
.minorkey t9
&pva-all.&all-min-8-2*.a255 &vel.d64a140
.minoroct o-1
.minorkey t31
&pva-all.&all-min-8-3*.a255 &vel.d64a140
&pva-all.&all-min-8-3*.a255 &vel.d64a140
@ switch to major in G to get the flatted seventh.
.majorkey t31
.majoroct o+0
&all-maj-8a. &vel.d64a255
.flu-pva-1 p20
.cel-pva-1 p20
&all-maj-8a. &vel.d64a200 d0a255
.majorkey t0
.fin-pva-1 p20
&all-maj-8b. &vel.d64a150 a255d0
&all-maj-8b. &vel.d64a150 a255d0
&all-maj-8b. &vel.d64a150 a255d0
&all-maj-8b. &vel.d64a150 a255d0
&all-maj-8b. &vel.d64a150 a255d0
&all-maj-8b. &vel.d64a150 a255d0
&all-maj-8b. &vel.d64a255 a155d0
&all-maj-8b. &vel.d64a255 a155d0
&all-maj-8b. &vel.d64a255 a150d0
&all-maj-8b. &vel.d64a255 a150d0
&all-maj-8b. &vel.d64a255 a150d0
@ vamp at very low intensity
@ what key to start:
.majorkey t0
.majoroct o+0
@ just a quick pause for the cause
@                                         17   43    9
&flu-allmaj-64-4-a. &fi2.v+6d0o4h64&majorkey.t+17 t+26 t+19d24 d0o4h48&majorkey.t+9 t+22 t+22d40 d0a255r0 &cel.d64r0 &fib.&majorkey.o-1d64  &fi3.d64r0 &dsp.d64r0 &ds2.d64r0 &vel.d64a200 d0a100
&all-maj-1a. &vel.d64a100 a180d0
&all-maj-1a. &vel.d64a155 a180d0
&all-maj-1a. &vel.d64a155 a180d0
&all-maj-1a. &vel.d64a145 a255d0
@
@ intro melody with more active bass
@
.dsx-ran r16
&all-maj-3x. &vel.d64a225
&all-maj-3a. &vel.d64a225
&all-maj-3b. &vel.d64a225
&all-maj-3c. &vel.d64a225
&all-maj-3d. &vel.d64a225
&flu-allmaj-32-1-e.
&all-maj-3e. &vel.d64a225
&all-maj-3f. &vel.d64a225
&all-maj-3g. &vel.d64a225
&all-maj-3h. &vel.d64a225
&all-maj-3i. &vel.d64a225
@ bridge
@ e minor
.flu-pva-1 p33
.cel-pva-1 p33
.fin-pva-1 p22
.dsp-pva-1 p25
.ds2-pva-1 p28
.dsx-ran r8
.minorkey t17
.minoroct o+0
&all-min-2a. &vel.a140d64 a255d0
&all-min-2b. &vel.a140d64 a255d0
@ a minor
.minorkey t39
.minoroct o-1
&all-min-2b. &vel.a140d64 a255d0
&all-min-2b. &vel.a140d64 a255d0
@ d minor
.minoroct o+0
.minorkey t8
&all-min-2b. &vel.a140d64 a255d0
&all-min-2b. &vel.a140d64 a255d0
.flu-pva-1 p2
.cel-pva-1 p2
.fin-pva-1 p2
@ G minor
.minoroct o-1
.minorkey t30
&all-min-2c. &vel.a200d64 a255d0
.flu-pva-1 p20
.cel-pva-1 p20
.fin-pva-1 p20
@ do we need this much repetition? twenty is plenty!
.majorkey t0
.majoroct o+0
&all-maj-8b. &vel.d64a130 d0a145
&all-maj-8b. &vel.d64a130 d0a145
&all-maj-8b. &vel.d64a130 d0a145
&all-maj-8b. &vel.d64a130 d0a145
&all-maj-8b. &vel.d64a150 d0a175
&all-maj-8b. &vel.d64a150 d0a175
&all-maj-8b. &vel.d64a170 d0a180
&all-maj-8b. &vel.d64a170 d0a180
&all-maj-8b. &vel.d64a190 d0a230
&all-maj-8b. &vel.d64a200 d0a255
@ music box arpeggio
.majorkey t0
.majoroct o+0
.dsx-ran r0
.dsp-ran-1 r0
.cel-ran-1 r7
.fin-pva-1 p2
.fin-env e16v+8
&all-maj-6a. &vel.d64a255
&all-maj-6a. &vel.d64a255
.majorkey t1
.fin-env e15v+13
&all-maj-6a. &vel.d64a255
.majorkey t2
.cel-ran-1 r0
&all-maj-6a. &vel.d64a255
.majorkey t3
&all-maj-6a. &vel.d64a255
.majorkey t4
&all-maj-6a. &vel.d64a255
.majorkey t5
&all-maj-6a. &vel.d64a255
.majorkey t4
&all-maj-6a. &vel.d64a255
.majorkey t3
&all-maj-6a. &vel.d64a255
.majorkey t2
&all-maj-6a. &vel.d64a255
.majorkey t1
&all-maj-6a. &vel.d64a255
.majorkey t0
&all-maj-6a. &vel.d64a128
.majorkey t1
&all-maj-6a. &vel.d64a64
.majorkey t2
&all-maj-6a. &vel.d64a32
&flu.d64r0 &fib.d64r0 &fi2.d64r0 &fi3.d64r0 &cel.d64r0 &ds2.d64r0 &dsp.d64r0 &vel.d64a1
