note_dict = {0: {'exec': chord_slide,
                 'mode1': 'oton',
                 'root1': '16/9',
                 'inv_1': 1, 
                 'rank1': 'A',
                 'mode2': 'oton', 
                 'root2': '16/15', 
                 'inv_2:' 1,
                 'rank2': 'A',
                 'repeats': 1,
                 'dur': 2, 
                 'hold': 2, 
                 'octv': rng.choice([3]), 
                 'defaults': defaults,
                 'gliss_type':'slide',
                 'env': 1,
                 'renv': 1,
                 'instruments': woodwinds},
              
            }